---
title: "D19200 - Trajectory analysis"
author: "Kai"
date: "13th January 2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(Seurat)
library(ggplot2)
library(slingshot)

#create theme to not duplicate code
theme_jb <- function(base_size=11) {
  (theme_bw() +
     theme(
       axis.title = element_text(size=11),
       axis.text = element_text(size=11),
       legend.text = element_text(size=11),
       #optional rotation of x-axis labels
       axis.text.x = element_text(angle=90, hjust=1,vjust=.5)
     ))
}

theme_jb_nogrid <- function(base_size=11) {
  (theme_bw() +
     theme(
       axis.title = element_text(size=11),
       axis.text = element_text(size=11),
       legend.text = element_text(size=11),
       #optional rotation of x-axis labels
       axis.text.x = element_text(angle=90, hjust=1,vjust=.5),
       panel.grid = element_blank(),
       panel.border = element_blank(),
       axis.line = element_line()
     ))
}
```

# Load Seurat Object from preprocessing

```{r}
OUTPUT = "~/tscr/kai/projects/01_SCC_scRNA/results/samples/cohort/D19200/rp/"
load(paste0(OUTPUT,"RData/D19200-tumornofibmono.RData"))
```

# Run Slingshot

```{r}
numberofPCs = 20 
red = "pca_SCT"
    
clusters <- as.character(D19200.tumor$seurat_clusters_tumor_SCT_PCA)
names(clusters) <- names(D19200.tumor$seurat_clusters_tumor_SCT_PCA)
# get embeddings (matrix of cells x PCs and PC values)
PCAembed <- Embeddings(D19200.tumor, reduction = red)[,1:numberofPCs]

#run slingshot
pt <- slingshot(PCAembed, clusterLabels = clusters)
```

## Plot curves on PCA in multiple dimensions

```{r}
# plot trajectories in pc space
colorfunc <- function(n) {
  ifelse(n>9,
         colors <- colorRampPalette(c("red","yellow"))(n),
         colors <- scales::hue_pal()(n)) 
  colors
}

colors <- colorfunc(length(levels(factor(clusters))))
names(colors) <- levels(factor(clusters))

ptcrv <- list()
ptcrv.nona <- list()
crv.numberofna <- list()
pt.colors <- list()
pt.plotdata <- list()
pt.pathdata <- list()
ptcrv.dimred <- list()
ptcrv.dimred.pt <- list()
for (crv in 1:dim(slingPseudotime(pt))[2]) {
  #vector of pseudotime with cellbarcodes as colnames
  ptcrv[[crv]] <- slingPseudotime(pt)[,crv]
  #throw out cells with NA
  ptcrv.nona[[crv]] <- ptcrv[[crv]][!is.na(ptcrv[[crv]])]
  #count NAs
  crv.numberofna[[crv]] <- sum(is.na(slingPseudotime(pt)[,crv])) / length(slingPseudotime(pt)[,crv])
  # Add pseudotime to Seuratobject
  D19200.tumor[[paste0(red,".crv",crv)]] <- ptcrv[[crv]]
  
  # color by cluster
  pt.colors[[crv]] <- clusters
  pt.colors[[crv]] <- factor(pt.colors[[crv]], levels= c("NA",levels(factor((pt.colors[[crv]])))))
  pt.colors[[crv]][is.na(slingPseudotime(pt)[,crv])] <- "NA"
  
  #plot curve on PCA plot  
  pt.plotdata[[crv]] <- as.data.frame(reducedDims(pt)[,1:2])
  pt.pathdata[[crv]] <- as.data.frame(slingCurves(pt)[[crv]]$s[slingCurves(pt)[[crv]]$ord,1:2])
  names(pt.plotdata[[crv]]) <- c("PC1","PC2")
  names(pt.pathdata[[crv]]) <- c("PC1","PC2")
  
  ptcrv.dimred[[crv]] <- ggplot() + 
    geom_point(data=pt.plotdata[[crv]],aes(x=PC1,y=PC2, col=pt.colors[[crv]])) +
    geom_path(data=pt.pathdata[[crv]],aes(x=PC1,y=PC2), col="black", size=1) +
    scale_color_manual(values = c("NA" = "black",colors)) +
    labs(x = "principal component 1", y = "principal component 2", title = paste0(red,"crv",crv)) +
    theme_jb_nogrid() 
  
  #colored by pseudotime from yellow to red
  ptcrv.dimred.pt[[crv]] <- ggplot() + 
    geom_point(data=pt.plotdata[[crv]],aes(x=PC1,y=PC2, col=ptcrv[[crv]])) +
    geom_path(data=pt.pathdata[[crv]],aes(x=PC1,y=PC2), col="black", size=1) +
    scale_color_gradient(low = "red",high = "yellow", limits = c(0,max(unlist(ptcrv),na.rm = T))) +
    labs(x = "principal component 1", y = "principal component 2", title = paste0(red,"crv",crv)) +
    theme_jb_nogrid() 
  
  ggsave(filename = paste0(OUTPUT,"figs-D19200/D19200-tumornofibmono-pt-",red,"-crv",crv,".svg"), ptcrv.dimred[[crv]],width = 5,height=5)
  ggsave(filename = paste0(OUTPUT,"figs-D19200/D19200-tumornofibmono-pt-",red,"-crv",crv,"-pt.svg"), ptcrv.dimred.pt[[crv]],width = 5,height=5)
  
  ggsave(filename = paste0(OUTPUT,"figs-D19200/D19200-tumornofibmono-pt-",red,"-crv",crv,"-noleg.svg"), ptcrv.dimred[[crv]] + theme(legend.position = "none") + labs(title = NULL),width = 5,height=5)
  ggsave(filename = paste0(OUTPUT,"figs-D19200/D19200-tumornofibmono-pt-",red,"-crv",crv,"-pt-noleg.svg"), ptcrv.dimred.pt[[crv]] + theme(legend.position = "none") + labs(title = NULL),width = 5,height=5)
}

#combining both trajectories in one plot
#colored by clusters
ptcrv.dimred.comb <- ggplot() + 
  geom_point(data=pt.plotdata[[1]],aes(x=PC1,y=PC2, col=clusters)) +
  geom_path(data=pt.pathdata[[1]],aes(x=PC1,y=PC2), col="black", size=1) +
  geom_path(data=pt.pathdata[[2]],aes(x=PC1,y=PC2), col="black", size=1) + 
  scale_color_manual(values = colors) +
  labs(x = "principal component 1 (4.5% variance)", y = "principal component 2 (1.5% variance)", title = paste0(red,"combined")) +
  theme_jb_nogrid()

ggsave(filename = paste0(OUTPUT,"figs-D19200/D19200-tumornofibmono-pt-",red,"-combined-clus.svg"), ptcrv.dimred.comb,width = 5,height=5)
ggsave(filename = paste0(OUTPUT,"figs-D19200/D19200-tumornofibmono-pt-",red,"-combined-clus-noleg.svg"), ptcrv.dimred.comb + theme(legend.position = "none") + labs(title = NULL),width = 5,height=5)

#colored by pseudotime
ptcrv.comb <- slingPseudotime(pt)[,1]
ptcrv.comb[is.na(ptcrv.comb)] <- slingPseudotime(pt)[,2][is.na(ptcrv.comb)]

ptcrv.dimred.comb.pt <- ggplot() + 
  geom_point(data=pt.plotdata[[1]],aes(x=PC1,y=PC2, col=ptcrv.comb)) +
  geom_path(data=pt.pathdata[[1]],aes(x=PC1,y=PC2), col="black", size=1) +
  geom_path(data=pt.pathdata[[2]],aes(x=PC1,y=PC2), col="black", size=1) +
  scale_color_gradient(low = "red",high = "yellow") +
  labs(x = "principal component 1", y = "principal component 2", title = paste0(red,"combined")) +
  theme_jb_nogrid()

ggsave(filename = paste0(OUTPUT,"figs-D19200/D19200-tumornofibmono-pt-",red,"-combined-pt.svg"), ptcrv.dimred.comb.pt, width = 5,height=5)
ggsave(filename = paste0(OUTPUT,"figs-D19200/D19200-tumornofibmono-pt-",red,"-combined-pt-noleg.svg"), ptcrv.dimred.comb.pt + theme(legend.position = "none") + labs(title = NULL),width = 5,height=5)

ptcrv.dimred.comb
ptcrv.dimred.comb.pt
crv.numberofna
```

# Visualize Cellular density along pseudotime

```{r}
#set colors to rainbow
ptcrv.hist.colors <- colorfunc(length(unique(clusters)))
names(ptcrv.hist.colors) <- seq(0,length(unique(clusters))-1,1)

ptcrv.hist <- list()
for (crv in 1:ncol(slingPseudotime(pt))) {
  #plot cell histogram across pseudotime
  ptcrv.hist[[crv]] <- ggplot(data=data.frame(pt=ptcrv.nona[[crv]],
                                              cluster=factor(clusters)[names(ptcrv.nona[[crv]])])) +
    geom_histogram(mapping = aes(x=pt,fill=cluster),
                   binwidth=1,
                   alpha=0.95,
                   position="stack") +
    coord_cartesian(xlim = c(0,max(unlist(ptcrv.nona))), ylim = c(0,165)) +
    scale_x_continuous(breaks=seq(0,2*max(unlist(ptcrv.nona)),signif(max(unlist(ptcrv.nona))/20,digits=1))) +
    scale_y_continuous(breaks=seq(0,200,10)) +
    scale_fill_manual(values = ptcrv.hist.colors) +
    ggtitle(paste0("Curve ",crv)) +
    theme_jb() +
    theme(panel.grid.minor = element_blank())
  
  ggsave(filename = paste0(OUTPUT,"figs-D19200/D19200-tumornofibmono-pt-",red,"-crv",crv,"-density.svg"),ptcrv.hist[[crv]], width = 5,height=5)
  ggsave(filename = paste0(OUTPUT,"figs-D19200/D19200-tumornofibmono-pt-",red,"-crv",crv,"-density-noleg.svg"),ptcrv.hist[[crv]] + theme(legend.position = "none") + labs(title = NULL), width = 5,height=5)
}

ptcrv.hist
```

# Save

```{r}
#save seurat object
save(file = paste0(OUTPUT,"RData/D19200-tumornofibmono-pseudotimeseurat.RData"),D19200.tumor)
#sessioninfo
writeLines(capture.output(sessionInfo()), paste0(OUTPUT,"RData/04-D19200-tumornofibmono-pseudotime-sessionInfo.txt"))
```
