---
title: "D19200 - inferCNV"
author: "Kai"
date: "13th January 2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Code for running inferCNV

```{r}
library(Seurat)
library(infercnv)

OUTPUT = "~/tscr/kai/projects/01_SCC_scRNA/results/samples/cohort/D19200/rp/"
OUTPUTINFERCNV <- paste0(OUTPUT,"inferCNV/")
load(paste0(OUTPUT,"RData/D19200-filt.RData"))

cell.names <-  colnames(D19200.filt)
counts_matrix <- GetAssayData(D19200.filt, assay = "RNA", slot = "counts")

annotation_df <- D19200.filt@meta.data[cell.names, "CellType", drop = F]
write.table(annotation_df, paste0(OUTPUTINFERCNV,"/firstSCC-filt_annotation.txt"), sep = "\t", col.names = F, row.names = T, quote = F)
rm(D19200.filt)

infer_cnvs_obj <- CreateInfercnvObject(raw_counts_matrix = as.matrix(counts_matrix),
                                       annotations_file = paste0(OUTPUTINFERCNV,"/firstSCC-filt_annotation.txt"),
                                       delim = "\t",
                                       gene_order_file = "~/tscr/Peiffer/2 Projects/10x/hg19_genes_noDuplicates.bed",
                                       ref_group_names = c("Fibroblasts","Endothelial Cells","Monocytes","Dendritic Cells"))

infer_cnvs <- infercnv::run(infer_cnvs_obj,
                            cutoff = 0.1,
                            out_dir = paste0(OUTPUTINFERCNV,"/infercnv"),
                            cluster_by_groups = T,
                            denoise = T,
                            HMM = F,
                            analysis_mode='samples')
```

from here, local analysis of inferCNV data

```{r}
library(Seurat)
library(ggplot2)
library(dplyr)
library(infercnv)
library(ComplexHeatmap)
library(scales)

theme_jb <- function(base_size=11) {
  (theme_bw() +
     theme(
       axis.title = element_text(size=11),
       axis.text = element_text(size=11),
       legend.text = element_text(size=11),
       #optional rotation of x-axis labels
       axis.text.x = element_text(angle=90, hjust=1,vjust=.5)
     ))
}
```

#Load data

```{r}
OUTPUT = "~/tscr/kai/projects/01_SCC_scRNA/results/samples/cohort/D19200/rp/"
OUTPUTINFERCNV <- paste0(OUTPUT,"inferCNV/infercnv/") #here put the infercnv data with all output

#load all cells
load(paste0(OUTPUT,"RData/D19200-filt.RData"))
#load tumor subset
load(paste0(OUTPUT,"RData/D19200-tumornofibmono.RData"))
#load infercnv results
infer_cnvs <- readRDS(paste0(OUTPUTINFERCNV,"run.final.infercnv_obj"))
```

# Extract inferCNV data

```{r}
#all cells
infercnv.data <- t(infer_cnvs@expr.data)
# Only use autosomes
infercnv.data.auto <- infercnv.data[,rownames(infer_cnvs@gene_order)[!as.character(infer_cnvs@gene_order$chr) %in% c("MT")]]

#Observation cells
observation.data <- t(infer_cnvs@expr.data[,unlist(infer_cnvs@observation_grouped_cell_indices)])
# without mitochondrial genome
observation.data.auto <- observation.data[,rownames(infer_cnvs@gene_order)[!as.character(infer_cnvs@gene_order$chr) %in% c("MT")]]
```

# Heatmap with standard hierarchical clustering

```{r}
#Heatmap with all cells
infercnv.all.hm <- Heatmap(infercnv.data.auto,
                           name="log2",
                           col = circlize::colorRamp2(breaks = c(min(infercnv.data.auto),0.85,1,1.15,max(infercnv.data.auto)),
                                                      colors = c("darkblue","blue","white","red","darkred")),
                           show_column_names = F,
                           show_row_names = F,
                           #column clustering and split
                           column_split = factor(paste0("chr",as.character(infer_cnvs@gene_order$chr)[!as.character(infer_cnvs@gene_order$chr) %in% c("MT")]), levels=paste0("chr",c(as.character(1:22),"X","Y"))),
                           column_order = rownames(infer_cnvs@gene_order)[!as.character(infer_cnvs@gene_order$chr) %in% c("MT")],
                           column_title_rot = 90,
                           column_title_side = "bottom",
                           cluster_columns = F,
                           cluster_column_slices = F,
                           #row clustering and split
                           row_split = factor(D19200.filt$CellType, levels=c("Fibroblasts","Dendritic Cells","Monocytes","Endothelial Cells","Tumor")),
                           row_title_rot = 0,
                           cluster_rows = T,
                           cluster_row_slices = F,
                           clustering_method_rows =  "ward.D2",
                           clustering_distance_rows = "euclidean",
                           #graphic options
                           row_names_gp = gpar(fontsize=11),
                           column_names_gp = gpar(fontsize=11),
                           row_title_gp = gpar(fontsize=11),
                           heatmap_legend_param = list(title_gp = gpar(fontsize=11), labels_gp = gpar(fontsize=11)),
                           #row_dend_width = unit("1","in"),
                           border = T,
                           border_gp = gpar(lwd=0.5),
                           use_raster = T,
                           raster_device = "CairoPNG",
                           raster_quality = 4,
                           width = unit("4.375","in"),
                           height = unit("5","in"))

pdf(paste0(OUTPUT,"figs-D19200/D19200-all-inferCNVauto_all_hm.pdf"), width=20, height=20)
infercnv.all.hm
dev.off()
```

# Heatmap of tumor cells only

```{r}
#colors for tumor cluster
colorfunc <- function(n) {
  ifelse(n>9,
         colors <- colorRampPalette(c("red","yellow"))(n),
         colors <- hue_pal()(n)) 
  colors
}

clustercolors <- colorfunc(length(levels(factor(D19200.tumor$seurat_clusters_tumor_SCT_PCA))))
names(clustercolors) <- levels(factor(D19200.tumor$seurat_clusters_tumor_SCT_PCA))

#select only cells that are within tumor (no fibro/mono cells)
tumor.data.auto <- observation.data.auto[names(D19200.tumor$orig.ident),]

#Annotation of Seurat clusters
leftanno <- HeatmapAnnotation(df = data.frame(clusters=D19200.tumor$seurat_clusters_tumor_SCT_PCA),
                              col = list(clusters=clustercolors),
                              which = "row")

# Heatmap only with tumor cells
infercnv.tumor.hm <- Heatmap(tumor.data.auto,
                             name="log2",
                             col = circlize::colorRamp2(breaks = c(min(tumor.data.auto),0.85,1,1.15,max(tumor.data.auto)),colors = c("darkblue","blue","white","red","darkred")),
                             show_column_names = F,
                             show_row_names = F,
                             #column clustering and split
                             column_split = factor(paste0("chr",as.character(infer_cnvs@gene_order$chr)[!as.character(infer_cnvs@gene_order$chr) %in% c("MT")]), levels=paste0("chr",c(as.character(1:22),"X","Y"))),
                             column_order = rownames(infer_cnvs@gene_order)[!as.character(infer_cnvs@gene_order$chr) %in% c("MT")],
                             column_title_rot = 90,
                             column_title_side = "bottom",
                             cluster_columns = F,
                             cluster_column_slices = F,
                             #row clustering and split
                             cluster_rows = T,
                             cluster_row_slices = T,
                             clustering_method_rows =  "ward.D2",
                             clustering_distance_rows = "euclidean",
                             row_dend_reorder = T,
                             #annotation
                             left_annotation = leftanno,
                             #graphic options
                             row_names_gp = gpar(fontsize=11),
                             column_names_gp = gpar(fontsize=11),
                             row_title_gp = gpar(fontsize=11),
                             heatmap_legend_param = list(title_gp = gpar(fontsize=11), labels_gp = gpar(fontsize=11)),
                             row_dend_width = unit("4","cm"),
                             border = T,
                             use_raster = T,
                             raster_device = "CairoPNG",
                             raster_quality = 4,
                             width = unit("9.375","in"),
                             height = unit("5","in"))

pdf(paste0(OUTPUT,"figs-D19200/D19200-tumor-inferCNVauto_hm.pdf"), width=20, height=20)
infercnv.tumor.hm
dev.off()
```

## Heatmaps sorted by pseudotime

load in pseudotime object from other script
```{r}
D19200.tumor.diffexpr <- D19200.tumor
load(paste0(OUTPUT,"RData/D19200-tumornofibmono-pseudotimeseurat.RData"))
D19200.tumor.diffexpr$pca_SCT.crv1 <- D19200.tumor$pca_SCT.crv1
D19200.tumor.diffexpr$pca_SCT.crv2 <- D19200.tumor$pca_SCT.crv2
D19200.tumor <- D19200.tumor.diffexpr

ptcrv1 <- D19200.tumor$pca_SCT.crv1
#same ordering as heatmap data
ptcrv1 <- ptcrv1[rownames(tumor.data.auto)]

ptcrv2 <- D19200.tumor$pca_SCT.crv2
#same ordering as heatmap data
ptcrv2 <- ptcrv2[rownames(tumor.data.auto)]
```

```{r}
leftanno.crv1 <- HeatmapAnnotation(df = data.frame(clusters=D19200.tumor$seurat_clusters_tumor_SCT_PCA[!is.na(ptcrv1)]),
                                   col = list(clusters=clustercolors),
                                   which = "row")
leftanno.crv2 <- HeatmapAnnotation(df = data.frame(clusters=D19200.tumor$seurat_clusters_tumor_SCT_PCA[!is.na(ptcrv2)]),
                                   col = list(clusters=clustercolors),
                                   which = "row")


infercnv.tumor.hm.crv1 <- Heatmap(tumor.data.auto[!is.na(ptcrv1),],
                                      name="log2",
                                      col = circlize::colorRamp2(breaks = c(min(tumor.data.auto),0.85,1,1.15,max(tumor.data.auto)),colors = c("darkblue","blue","white","red","darkred")),
                                      show_column_names = F,
                                      show_row_names = F,
                                      #column clustering and split
                                      column_split = factor(paste0("chr",as.character(infer_cnvs@gene_order$chr)[!as.character(infer_cnvs@gene_order$chr) %in% c("MT")]), levels=paste0("chr",c(as.character(1:22),"X","Y"))),
                                      column_order = rownames(infer_cnvs@gene_order)[!as.character(infer_cnvs@gene_order$chr) %in% c("MT")],
                                      column_title_rot = 90,
                                      column_title_side = "bottom",
                                      cluster_columns = F,
                                      cluster_column_slices = F,
                                      #row clustering and split
                                      cluster_rows = F,
                                      cluster_row_slices = F,
                                      #row_split = is.na(ptcrv2),
                                      #row_title = c("on crv","not on crv (not sorted)"),
                                      row_title_rot = 0,
                                      row_order = names(ptcrv1[!is.na(ptcrv1)][order(ptcrv1[!is.na(ptcrv1)])]),
                                      #annotation
                                      left_annotation = leftanno.crv1,
                                      #graphic options
                                      row_names_gp = gpar(fontsize=11),
                                      column_names_gp = gpar(fontsize=11),
                                      row_title_gp = gpar(fontsize=11),
                                      heatmap_legend_param = list(title_gp = gpar(fontsize=11), labels_gp = gpar(fontsize=11)),
                                      row_dend_width = unit("4","cm"),
                                      border = T,
                                      use_raster = T,
                                      raster_device = "CairoPNG",
                                      raster_quality = 4,
                                      heatmap_width = unit("4","in"),
                                      heatmap_height = unit("5","in"))

infercnv.tumor.hm.crv2 <- Heatmap(tumor.data.auto[!is.na(ptcrv2),],
                                      name="log2",
                                      col = circlize::colorRamp2(breaks = c(min(tumor.data.auto),0.85,1,1.15,max(tumor.data.auto)),colors = c("darkblue","blue","white","red","darkred")),
                                      show_column_names = F,
                                      show_row_names = F,
                                      #column clustering and split
                                      column_split = factor(paste0("chr",as.character(infer_cnvs@gene_order$chr)[!as.character(infer_cnvs@gene_order$chr) %in% c("MT")]), levels=paste0("chr",c(as.character(1:22),"X","Y"))),
                                      column_order = rownames(infer_cnvs@gene_order)[!as.character(infer_cnvs@gene_order$chr) %in% c("MT")],
                                      column_title_rot = 90,
                                      column_title_side = "bottom",
                                      cluster_columns = F,
                                      cluster_column_slices = F,
                                      #row clustering and split
                                      cluster_rows = F,
                                      cluster_row_slices = F,
                                      #row_split = is.na(ptcrv2),
                                      #row_title = c("on crv","not on crv (not sorted)"),
                                      row_title_rot = 0,
                                      row_order = names(ptcrv2[!is.na(ptcrv2)][order(ptcrv2[!is.na(ptcrv2)])]),
                                      #annotation
                                      left_annotation = leftanno.crv2,
                                      #graphic options
                                      row_names_gp = gpar(fontsize=11),
                                      column_names_gp = gpar(fontsize=11),
                                      row_title_gp = gpar(fontsize=11),
                                      heatmap_legend_param = list(title_gp = gpar(fontsize=11), labels_gp = gpar(fontsize=11)),
                                      row_dend_width = unit("4","cm"),
                                      border = T,
                                      use_raster = T,
                                      raster_device = "CairoPNG",
                                      raster_quality = 4,
                                      heatmap_width = unit("4","in"),
                                      heatmap_height = unit("5","in"))

pdf(paste0(OUTPUT,"figs-D19200/D19200-tumor-inferCNVauto_obs_hm_ptcrv1.pdf"), width=20, height=20)
infercnv.tumor.hm.crv1
dev.off()
pdf(paste0(OUTPUT,"figs-D19200/D19200-tumor-inferCNVauto_obs_hm_ptcrv2.pdf"), width=20, height=20)
infercnv.tumor.hm.crv2
dev.off()
```

# Quantified measure of CNV amount to identify tumor cells

## Standard deviation from reference

```{r}
library(ggpubr)
# first, get the mean expression value of the reference cells
refmeans <- apply(infercnv.data.auto[names(D19200.filt$CellType[D19200.filt$CellType!="Tumor"]),],1,mean)
refmean <- mean(refmeans)

#calculate a standard deviation of each cells against the mean of the reference cells to define CNV strength by smoothed mean expression differences
refsdpercell <- lapply(unique(D19200.filt$CellType),function(x) apply(infercnv.data.auto,1,function(x) sum((x-refmean)^2) / length(x))[names(D19200.filt$CellType[D19200.filt$CellType==x])])
names(refsdpercell) <- unique(D19200.filt$CellType)

#remove one NA value
refsdpercell <- lapply(refsdpercell,function(x) x[!is.na(x)])
refsdpercell.df <- do.call(rbind,lapply(names(refsdpercell),function(x) data.frame(score=refsdpercell[[x]],CellType=x)))
refsdpercell.df$CellType[refsdpercell.df$CellType!="Tumor"] <- "non-Tumor"

#ViolinPlot Tumor vs all others
refsdpercell.vln <- ggplot(data=refsdpercell.dfall, mapping = aes(x=CellType,y=score)) +
  geom_violin(fill="blue",col="black") +
  geom_jitter(size=0.25) +
  #stat_compare_means(method = "t.test",paired = F) +
  labs(x="",y="standard deviation from reference") +
  theme_jb()

ggsave(filename = paste0(OUTPUT,"figs-D19200/D19200-inferCNV-refsdviolin.svg"),refsdpercell.vln,device = "svg", width=5, height=5)
refsdpercell.vln
```

# Save

```{r}
# workspace image
save.image(file = paste0(OUTPUT,"RData/D19200-all-inferCNV-clustering.RData"))
#sessionInfo
writeLines(capture.output(sessionInfo()), paste0(OUTPUT,"RData/17-D19200-all-inferCNV-sessionInfo.txt"))
```
