---
title: "D19200 - preprocessing"
author: "Kai"
date: "13th January 2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

#Load

```{r}
library(Seurat)
OUTPUT = "~/tscr/kai/projects/01_SCC_scRNA/results/samples/cohort/D19200/rp/"

#all cells
load(paste0(OUTPUT,"RData/D19200-filt.RData"))
#fibroendo annotation
load(paste0(OUTPUT,"RData/D19200-fibroendo.RData"))
D19200.ef$type[D19200.ef$type=="Endothelial Cells"] <- "endo"
#myeloid annotation
load(paste0(OUTPUT,"RData/D19200-mynot.RData"))
#tumor annotation
load(paste0(OUTPUT,"RData/D19200-tumornofibmono-pseudotimeseurat.RData"))

D19200.tumor$trajectorycluster <- as.character(D19200.tumor$seurat_clusters_tumor_SCT_PCA)
D19200.tumor$trajectorycluster[D19200.tumor$trajectorycluster=="0"] <- "6 temp"
D19200.tumor$trajectorycluster[D19200.tumor$trajectorycluster=="1"] <- "3 temp"
D19200.tumor$trajectorycluster[D19200.tumor$trajectorycluster=="2"] <- "4 temp"
D19200.tumor$trajectorycluster[D19200.tumor$trajectorycluster=="3"] <- "2 temp"
D19200.tumor$trajectorycluster[D19200.tumor$trajectorycluster=="4"] <- "1 temp"
D19200.tumor$trajectorycluster[D19200.tumor$trajectorycluster=="5"] <- "7 temp"
D19200.tumor$trajectorycluster[D19200.tumor$trajectorycluster=="6"] <- "5 temp"
D19200.tumor$trajectorycluster <- sub(" temp","",D19200.tumor$trajectorycluster)
D19200.tumor$trajectorycluster <- factor(D19200.tumor$trajectorycluster)

#merge annotations
D19200.filt$CellType_metadata <- as.character(D19200.filt$CellType)
D19200.filt$CellType_metadata[names(D19200.mynot$TMEsub)] <- as.character(D19200.mynot$TMEsub)
D19200.filt$CellType_metadata[names(D19200.ef$type)] <- as.character(D19200.ef$type)
D19200.filt$CellType_metadata[names(D19200.tumor$trajectorycluster)] <- paste0("Tumor-",as.character(D19200.tumor$trajectorycluster))

#All cell types not renamed were filtered in subsets as misclassified, so rename accordingly
D19200.filt$CellType_metadata[D19200.filt$CellType_metadata=="Dendritic Cells"] <- "Dend-misclassified"
D19200.filt$CellType_metadata[D19200.filt$CellType_metadata=="Macrophages"] <- "Macro-misclassified"
D19200.filt$CellType_metadata[D19200.filt$CellType_metadata=="Fibroblasts"] <- "CAF-misclassified"
D19200.filt$CellType_metadata[D19200.filt$CellType_metadata=="Tumor"] <- "Tumor-misclassified"

metadata.df <- data.frame(cell= names(D19200.filt$CellType_metadata),
                          celltype_classification=D19200.filt$CellType_metadata)

write.csv(x = metadata.df,file = paste0(OUTPUT,"celltype_metadata.csv"),row.names = F,col.names = F)

```
