---
title: "allSCC - dorothea"
author: "Kai"
date: "13th January 2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(Seurat)
library(dorothea)
library(ggplot2)

source(paste0("~/tscr/kai/projects/01_SCC_scRNA/results/functions.R"))
OUTPUT = "~/tscr/kai/projects/01_SCC_scRNA/results/alldatasets/"
```

# Code to run dorothea on cluster

```{r eval=FALSE, include=FALSE}
Rdir="/omics/groups/OE0460/internal/Kai2/R-4.1.0-packages"
library("Seurat", lib.loc=Rdir)
library("dorothea",lib.loc=Rdir)

OUTPUT = "/omics/groups/OE0460/internal/Kai2/allSCC-dorothea/"
load(paste0(OUTPUT,"alltumor-all-perpatient.RData"))

DefaultAssay(SCC) <- "SCT"
regulon <- get(data(dorothea_hs, package = "dorothea"))

set.seed(42)
SCC <- run_viper(SCC, regulon,
                     options = list(method = "scale",
                                    pleiotropy = F, # default
                                    nes = T, #default
                                    bootstraps = 0, #default
                                    minsize = 4, 
                                    eset.filter = F,
                                    cores = 30, 
                                    verbose = T),
                     assay_key = "SCT")

save(file = paste0(OUTPUT,"alltumor-dorothea.RData"),SCC)
writeLines(capture.output(sessionInfo()), paste0(OUTPUT,"alltumor-dorothea-sessionInfo.txt"))
```

# DoRothEA analysis

```{r}
load(paste0(OUTPUT,"RData/alltumor-dorothea.RData"))

DefaultAssay(SCC) <- "dorothea"
EMTTFs <- c("ZEB1","ZEB2","SNAI1","SNAI2","TWIST1","TWIST2")
```

## Expression of TFs in tumor cells

```{r}
#TFs as Violin Plot
TFs.vln <- VlnPlot(SCC,
                   features = EMTTFs,
                   group.by = "epitype_ov",
                   assay = "RNA",
                   slot = "data",
                   pt.size = 0.1,
                   combine = F)
TFs.vln <- lapply(TFs.vln, function(x) x + labs(x="",y="expression") + theme_jb_nogrid() + theme(axis.text.x = ))
names(TFs.vln) <- EMTTFs

lapply(names(TFs.vln), function(x) ggsave(filename = paste0(OUTPUT,"figs/alltumor-RNAdata-VLN-TF-",x,".svg"),TFs.vln[[x]],width = 4,height = 2.5))
lapply(names(TFs.vln), function(x) ggsave(filename = paste0(OUTPUT,"figs/alltumor-RNAdata-VLN-TF-",x,"-noleg.svg"),TFs.vln[[x]] + theme(legend.position = "none") + ggtitle(NULL),width = 4,height = 3))

#percentage of cells expressing certain TF
expr.RNAdata <- SCC@assays$RNA@data
TF.perc <- unlist(lapply(EMTTFs, function(TF) sum(expr.RNAdata[TF,]>0) / length(expr.RNAdata[TF,]>0)))
names(TF.perc) <- EMTTFs

TF.perc.barplot <- ggplot(mapping = aes(x=factor(names(TF.perc),levels=names(TF.perc)),y=TF.perc)) +
  geom_bar(stat="identity") +
  coord_cartesian(ylim=c(0,1)) +
  scale_y_continuous(breaks=seq(0,1,0.1)) +
  labs(x="", y="% expr. tumor cells") +
  theme_jb() +
  theme(panel.grid.minor = element_blank(),axis.text.y = element_text(size = 9))
ggsave(filename = paste0(OUTPUT,"figs/alltumor-RNAdata-TF-perc.svg"),TF.perc.barplot,width = 1.5,height = 3)
```

## Summarize by pattumortype and Lokalisation

```{r}
SCC$pattypeLok <- paste0(SCC$pattumortype,"_",SCC$Lok)
```

### Mean Activity per cluster for EMT TF activity

```{r}
library(tidyr)
library(tibble)
library(dplyr)
## Summarise cluster
## We transform Viper scores, scaled by seurat, into a data frame to better 
## handling the results
viper_scores_df <- GetAssayData(SCC, 
                                slot = "data", 
                                assay = "dorothea") %>%
  data.frame(check.names = F) %>%
  t()

## We create a data frame containing the cells and their clusters
CellsClusters <- data.frame(cell = names(SCC$pattypeLok), 
                            cell_type = as.character(SCC$pattypeLok),
                            check.names = F)

## We create a data frame with the Viper score per cell and its clusters
viper_scores_clusters <- viper_scores_df  %>%
  data.frame() %>% 
  rownames_to_column("cell") %>%
  gather(tf, activity, -cell) %>%
  inner_join(CellsClusters)

## We summarize the Viper scores by cellpopulation
summarized_viper_scores <- viper_scores_clusters %>% 
  group_by(tf, cell_type) %>%
  summarise(avg = mean(activity),
            std = sd(activity))

dtsum.df <- reshape2::dcast(as.data.frame(summarized_viper_scores),tf ~ cell_type,value.var = "avg")
rownames(dtsum.df) <- dtsum.df[,1]
dtsum.df <- dtsum.df[,-1]
```

```{r}
EMTdtsum.df <- dtsum.df[EMTTFs,]

#just show PT and MET (remove NA) and EMP clusters
EMTdtsum.df <- EMTdtsum.df[,grep("NA",c(grep("pEMT",colnames(EMTdtsum.df),value = T),grep("epi",colnames(EMTdtsum.df),value = T)),invert = T,value = T)]
colnames(EMTdtsum.df) <- gsub(" [(]CXCL9[/]10[/]11[)]","",colnames(EMTdtsum.df))
  
EMTdtsum.df.Lok <- unlist(lapply(strsplit(colnames(EMTdtsum.df),split = "_"),function(x) x[3]))
names(EMTdtsum.df.Lok) <- colnames(EMTdtsum.df)
EMTdtsum.df.emo <- unlist(lapply(strsplit(colnames(EMTdtsum.df),split = "_"),function(x) x[2]))
EMTdtsum.df.pat <- unlist(lapply(strsplit(colnames(EMTdtsum.df),split = "_"),function(x) x[1]))

#change annotation
colnames(EMTdtsum.df) <- paste0(EMTdtsum.df.pat,"_",EMTdtsum.df.Lok,"_",EMTdtsum.df.emo)
#simplify for  emp annotation
EMTdtsum.df.emo.ann <- unlist(lapply(strsplit(EMTdtsum.df.emo,split = "-"),function(x) ifelse(length(grep("pEMT",x))>0,x[grep("pEMT",x)],x[1])))

EMTdtsum.df.cb <- c(-max(c(abs(min(EMTdtsum.df)),abs(max(EMTdtsum.df)))),0,max(c(abs(min(EMTdtsum.df)),abs(max(EMTdtsum.df)))))

library(ComplexHeatmap)
library(RColorBrewer)
bottomanno <- HeatmapAnnotation(df = data.frame(Loc = factor(EMTdtsum.df.Lok,levels = c("PT","MET")),
                                                EMP = factor(EMTdtsum.df.emo.ann)),
                                col = list(Loc=colorfunc(c("PT","MET")),
                                           EMP=colorfunc(c("pEMT","epi","temp"),brewer = T)[1:2]))

EMTdtsum.df.hm <- Heatmap(EMTdtsum.df,
                          name=" ",
                          col=circlize::colorRamp2(breaks=EMTdtsum.df.cb, colors = c("purple", "black", "yellow")),
                          show_column_names = T,
                          show_row_names = T,
                          cluster_columns = F,
                          column_split = EMTdtsum.df.pat,
                          cluster_rows = F,
                          #graphic options
                          column_title_rot = 90, 
                          bottom_annotation = bottomanno,
                          column_labels = gsub("-","",gsub("epi","",gsub("pEMT","",EMTdtsum.df.emo))),
                          row_names_gp = gpar(fontsize=10),
                          column_names_gp = gpar(fontsize=10),
                          row_title_gp = gpar(fontsize=10),
                          column_title_gp = gpar(fontsize=10),
                          heatmap_legend_param = list(title_gp = gpar(fontsize=10), labels_gp = gpar(fontsize=9)),
                          border = T,
                          use_raster = T,
                          raster_device = "CairoPNG",
                          raster_quality = 4,
                          width = unit(5.7,"in"),
                          height = unit(1.5,"in")
)

pdf(paste0(OUTPUT,"figs/alltumor-dtEMTsum-HM-pattypeLok.pdf"), width=15, height=10)
EMTdtsum.df.hm
dev.off()
```

### Mean expression per cluster for CDH1 and SPRR1B Heatmap

```{r}
library(tidyr)
library(tibble)
library(dplyr)
## Summarise cluster
## We transform Viper scores, scaled by seurat, into a data frame to better 
## handling the results
RNAdata.df <- GetAssayData(SCC, 
                                slot = "data", 
                                assay = "RNA") %>%
  data.frame(check.names = F) %>%
  t()

## We create a data frame containing the cells and their clusters
CellsClusters <- data.frame(cell = names(SCC$pattypeLok), 
                            cell_type = as.character(SCC$pattypeLok),
                            check.names = F)

## We create a data frame with the Viper score per cell and its clusters
RNAdata.df_clusters <- RNAdata.df  %>%
  data.frame() %>% 
  rownames_to_column("cell") %>%
  gather(gene, expression, -cell) %>%
  inner_join(CellsClusters)

## We summarize the Viper scores by cellpopulation
summarized_RNAdata <- RNAdata.df_clusters %>% 
  group_by(gene, cell_type) %>%
  summarise(avg = mean(expression),
            std = sd(expression))

RNAsum.df <- reshape2::dcast(as.data.frame(summarized_RNAdata),gene ~ cell_type,value.var = "avg")
rownames(RNAsum.df) <- RNAsum.df[,1]
RNAsum.df <- RNAsum.df[,-1]
```

```{r}
emtexpr <- RNAsum.df[c("CDH1","SPRR1B"),]

emtexpr <- emtexpr[,grep("NA",c(grep("pEMT",colnames(emtexpr),value = T),grep("epi",colnames(emtexpr),value = T)),invert = T,value = T)]
colnames(emtexpr) <- gsub(" [(]CXCL9[/]10[/]11[)]","",colnames(emtexpr))

emtexpr.cb <- c(0,max(emtexpr))

Lokanno <- unlist(lapply(strsplit(colnames(emtexpr),split = "_"),function(x) x[2]))
names(Lokanno) <- colnames(emtexpr)

emtexpr.hm <- Heatmap(emtexpr,
                          name=" ",
                          col=circlize::colorRamp2(breaks=emtexpr.cb, colors = c("white", "red")),
                          show_column_names = T,
                          show_row_names = T,
                          cluster_columns = F,
                          cluster_rows = F,
                          column_split = EMTdtsum.df.pat,
                          #graphic options
                          column_title_rot = 90,
                          row_names_gp = gpar(fontsize=10),
                          column_names_gp = gpar(fontsize=10),
                          row_title_gp = gpar(fontsize=10),
                          column_title_gp = gpar(fontsize=10),
                          heatmap_legend_param = list(title_gp = gpar(fontsize=10), labels_gp = gpar(fontsize=9)),
                          border = T,
                          use_raster = T,
                          raster_device = "CairoPNG",
                          raster_quality = 4,
                          width = unit(5.7,"in"),
                          height = unit(0.25,"in")
)

pdf(paste0(OUTPUT,"figs/alltumor-RNAdata-pattypeLok-CDH1-SPRR1B.pdf"), width=10, height=10)
emtexpr.hm
dev.off()
```

#summarize by patient

```{r}
SCC$pattype <- paste0(SCC$epitype_ov,"_",SCC$patients)
```


```{r}
library(tidyr)
library(tibble)
library(dplyr)
## Summarise cluster
## We transform Viper scores, scaled by seurat, into a data frame to better
## handling the results
viper_scores_df <- GetAssayData(SCC,
                                slot = "data",
                                assay = "dorothea") %>%
  data.frame(check.names = F) %>%
  t()

## We create a data frame containing the cells and their clusters
CellsClusters <- data.frame(cell = names(SCC$pattype),
                            cell_type = as.character(SCC$pattype),
                            check.names = F)

## We create a data frame with the Viper score per cell and its clusters
viper_scores_clusters <- viper_scores_df  %>%
  data.frame() %>%
  rownames_to_column("cell") %>%
  gather(tf, activity, -cell) %>%
  inner_join(CellsClusters)

## We summarize the Viper scores by cellpopulation
summarized_viper_scores <- viper_scores_clusters %>%
  group_by(tf, cell_type) %>%
  summarise(avg = mean(activity),
            std = sd(activity))

dtsum.df <- reshape2::dcast(as.data.frame(summarized_viper_scores),tf ~ cell_type,value.var = "avg")
rownames(dtsum.df) <- dtsum.df[,1]
dtsum.df <- dtsum.df[,-1]
```

### Visualization as Heatmap with summarised activity per cluster

```{r}
EMTdtsum.df <- dtsum.df[EMTTFs,]

EMTdtsum.df <- EMTdtsum.df[,c(grep("pEMT",colnames(EMTdtsum.df)),grep("epi",colnames(EMTdtsum.df)))]

EMTbpdata <- data.frame(ZEB1=as.numeric(EMTdtsum.df[1,]),
                        patient=unlist(lapply(strsplit(colnames(EMTdtsum.df),split = "_"),function(x) x[2])),
                        pt=unlist(lapply(strsplit(colnames(EMTdtsum.df),split = "_"),function(x) x[1])))

dtEMT.bp <- ggplot(data=EMTbpdata,aes(x=pt,y=ZEB1)) +
  geom_violin(fill="grey") +
  geom_point() +
  geom_path(mapping = aes(group=patient)) +
  labs(x=NULL, y="mean ZEB1 activity") +
  theme_jb() +
  theme(panel.grid.minor = element_blank(),panel.grid.major.x = element_blank())

ggsave(filename = paste0(OUTPUT,"figs/alltumor-dtEMT-VLN-pattype.svg"),dtEMT.bp + theme(legend.position = "none") + ggtitle(NULL),width = 1.5,height = 2.75)

dtEMT.bp
```
