---
title: "Downstream - Subsetting"
author: "Kai"
date: "10th May 2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(Seurat)
library(ggplot2)
library(ggrepel)
library(ComplexHeatmap)
library(RColorBrewer)
library(fgsea)
library(cowplot)
library(dplyr)

source(paste0("~/tscr/kai/projects/01_SCC_scRNA/results/functions.R"))
OUTPUT = "~/tscr/kai/projects/01_SCC_scRNA/results/pubdatasets/kuertendata/HPVneg_CD45n_analysis/"
```

# Load Seurat Object from preprocessing

```{r}
load(paste0(OUTPUT,"RData/HNSCC-fibrofilt.RData"))
```

## Annotation

```{r}
HNSCC.f$fibrotype <- as.character(HNSCC.f$seurat_clusters_fibrofilt_SCTccmito_PCA_harmony_res4)
HNSCC.f$fibrotype[HNSCC.f$fibrotype=="0"] <- "Immune-1"
HNSCC.f$fibrotype[HNSCC.f$fibrotype=="1"] <- "Immune-2"
HNSCC.f$fibrotype[HNSCC.f$fibrotype=="2"] <- "Immune-2"
HNSCC.f$fibrotype[HNSCC.f$fibrotype=="3"] <- "Pericytes"
HNSCC.f$fibrotype[HNSCC.f$fibrotype=="4"] <- "FRCs"
HNSCC.f$fibrotype[HNSCC.f$fibrotype=="5"] <- "Immune-2"
HNSCC.f$fibrotype[HNSCC.f$fibrotype=="6"] <- "Immune-3"
HNSCC.f$fibrotype[HNSCC.f$fibrotype=="7"] <- "Immune-3"
HNSCC.f$fibrotype[HNSCC.f$fibrotype=="8"] <- "ECM"
HNSCC.f$fibrotype[HNSCC.f$fibrotype=="9"] <- "ECM"
HNSCC.f$fibrotype[HNSCC.f$fibrotype=="10"] <- "Immune-1"
HNSCC.f$fibrotype[HNSCC.f$fibrotype=="11"] <- "ECM"
HNSCC.f$fibrotype[HNSCC.f$fibrotype=="12"] <- "ECM"
HNSCC.f$fibrotype[HNSCC.f$fibrotype=="13"] <- "Immune-4"
HNSCC.f$fibrotype[HNSCC.f$fibrotype=="14"] <- "stress"
HNSCC.f$fibrotype[HNSCC.f$fibrotype=="15"] <- "stress"
HNSCC.f$fibrotype[HNSCC.f$fibrotype=="16"] <- "Pericytes"
HNSCC.f$fibrotype[HNSCC.f$fibrotype=="17"] <- "Myofibroblasts"
HNSCC.f$fibrotype[HNSCC.f$fibrotype=="18"] <- "Pericytes"
HNSCC.f$fibrotype[HNSCC.f$fibrotype=="19"] <- "Pericytes"
HNSCC.f$fibrotype[HNSCC.f$fibrotype=="20"] <- "Pericytes"
HNSCC.f$fibrotype[HNSCC.f$fibrotype=="21"] <- "ECM"
HNSCC.f$fibrotype[HNSCC.f$fibrotype=="22"] <- "ECM"
HNSCC.f$fibrotype[HNSCC.f$fibrotype=="23"] <- "Pericytes"
HNSCC.f$fibrotype[HNSCC.f$fibrotype=="24"] <- "Immune-3"
HNSCC.f$fibrotype[HNSCC.f$fibrotype=="25"] <- "Immune-1"
HNSCC.f$fibrotype[HNSCC.f$fibrotype=="26"] <- "Immune-3"
HNSCC.f$fibrotype[HNSCC.f$fibrotype=="27"] <- "stress"
HNSCC.f$fibrotype[HNSCC.f$fibrotype=="28"] <- "ECM"

#set levels and colors of fibrotype
HNSCC.f$fibrotype <- factor(HNSCC.f$fibrotype,levels=c("ECM","Immune-1","Immune-2","Immune-3","Immune-4","FRCs","Myofibroblasts","Pericytes","stress"))
fibrotypecolors <- c(scales::hue_pal()(6)[1],
                      colorRampPalette(c(scales::hue_pal()(6)[2],"lightgreen"))(6)[2:5],
                      scales::hue_pal()(6)[3:5],
                      "#888888")
names(fibrotypecolors) <- levels(HNSCC.f$fibrotype)

umapharmony.SCTccmito.fibrotype <- DimPlot(HNSCC.f,
                                            reduction="humap_SCTccmito",
                                            pt.size = 1,
                                            label = T,
                                            group.by = "fibrotype") + 
  scale_color_manual(values = fibrotypecolors) +
  labs(x="UMAP_1",y="UMAP_2",title=NULL) +
  theme_jb_nogrid()

ggsave(filename = paste0(OUTPUT,"figs/HNSCC-fibrofilt-SCTccmito-UMAPharmony-fibrotype-noleg.svg"),umapharmony.SCTccmito.fibrotype + theme(legend.position = "none"), width=5, height=5)
ggsave(filename = paste0(OUTPUT,"figs/HNSCC-fibrofilt-SCTccmito-UMAPharmony-fibrotype.svg"),umapharmony.SCTccmito.fibrotype, width=8, height=5)

umapharmony.SCTccmito.fibrotype + theme(legend.position = "none")
```

# Barplots and Pie charts

```{r}
HNSCC.f$patients <- factor(HNSCC.f$patients)
cellfrac.scRNA <- do.call(rbind,lapply(levels(HNSCC.f$patients)[levels(HNSCC.f$patients) %in% unique(HNSCC.f$patients)],function(x) table(HNSCC.f$fibrotype[HNSCC.f$patients==x])))
rownames(cellfrac.scRNA) <- levels(HNSCC.f$patients)[levels(HNSCC.f$patients) %in% unique(HNSCC.f$patients)]
#fractions
cellfrac.scRNA <- cellfrac.scRNA / rowSums(cellfrac.scRNA)

patientsorder <- rev(rownames(cellfrac.scRNA))

#stacked barplot of tumor phenotypes
cellfrac.scRNA.bp <- ggplot(data=reshape2::melt(cellfrac.scRNA)) +
  geom_bar(aes(x=Var1,
               y=value,
               fill=Var2),
           stat="identity",
           position = "stack") + #position_fill(reverse = T)) +
  scale_y_continuous(breaks = seq(0,1,0.1)) +
  scale_fill_manual(values = fibrotypecolors) +
  labs(x="",y="fraction",fill="types") +
  coord_flip(ylim = c(0,1)) +
  theme_jb()

ggsave(filename = paste0(OUTPUT,"figs/cellfraction-fibrotype-scRNA-bp.svg"),cellfrac.scRNA.bp, width=3.5, height=3.5)
ggsave(filename = paste0(OUTPUT,"figs/cellfraction-fibrotype-scRNA-bp-noleg.svg"),cellfrac.scRNA.bp + theme(legend.position = "none") + ggtitle(NULL), width=3, height=3.5)

patients.t <- as.data.frame(table(HNSCC.f$patients))

#number of cells per patient
patients.p <- ggplot(data=patients.t) +
  geom_bar(aes(x=Var1,
               y=Freq),
           stat="identity",
           position="stack") +
  labs(x="",y="number of cells") +
  scale_y_continuous(breaks = seq(0,2000,250)) +
  scale_fill_brewer(palette = "Set1") +
  coord_flip() +
  theme_jb()
    
ggsave(filename = paste0(OUTPUT,"figs/HNSCC-fibrofilt-patients-table.svg"),patients.p, width=5, height=4)

library(cowplot)
ggsave(filename = paste0(OUTPUT,"figs/HNSCC-fibrotype-overviewplot.svg"),
       plot_grid(plotlist = list(
         cellfrac.scRNA.bp + theme(panel.grid.minor.x = element_blank(),legend.position = "none"),
         patients.p + theme(axis.text.y = element_blank(),axis.ticks.y = element_blank(),legend.position = "none")),
         ncol=2,nrow=1,align = "h",labels=NULL,axis = "rlbt",rel_widths = c(3.5,1)),
  width=5,height=4.5)
```

```{r}
#calculate mean percentage of cells
piefrac.scRNA <- colMeans(cellfrac.scRNA)

scRNA.pie.PT <- ggplot(data=data.frame(value=piefrac.scRNA,
                                       Var=factor(names(piefrac.scRNA),levels = names(piefrac.scRNA))),
                       aes(x="",y=value,fill=Var)) +
  geom_bar(stat="identity", color="white") +
  scale_fill_manual(values = fibrotypecolors) +
  coord_polar("y",start=0) +
  theme_void()

ggsave(filename = paste0(OUTPUT,"figs/cellfraction-fibrotype-scRNA-pie-PT.svg"),scRNA.pie.PT,width = 5,height = 5)
```


# Check several interesting genes

## Scores, Heatmaps, Dotplots of several genes / gene signatures

```{r}
#set expression matrices and annotation objects for all Heatmaps
expr.RNAscaledata <- as.data.frame(GetAssayData(HNSCC.f, assay = "RNA", slot = "scale.data"))
bottomanno <- HeatmapAnnotation(df = data.frame(patient=HNSCC.f$patients),
                                col = list(patient=colorfunc(unique(HNSCC.f$patients))),
                                which = "column", annotation_name_side = "left")

genesofinterest <- list()
genesofinterest[["collagens"]] <- grep("^COL",rownames(HNSCC.f),value = T)
genesofinterest[["cytokines"]] <- c(grep("^IL",rownames(HNSCC.f),value = T),grep("^IFN",rownames(HNSCC.f),value = T),csfs <- grep("^CSF",rownames(HNSCC.f),value = T),"TNF")
genesofinterest[["chemokines"]] <- c(grep("^CXCL",rownames(HNSCC.f),value = T),grep("^CCL",rownames(HNSCC.f),value = T))
genesofinterest[["MHCII"]] <- c(grep("^HLA",rownames(HNSCC.f),value = T))
genesofinterest[["marker"]] <- c("MMP11","MMP1",paste0("CXCL",c(1,2,3,8,9,10,11,12,13,14)),"CCL2","CCL8","CCL19","CCL21","C3","C7","CFD","IL6","PLA2G2A","APOD","APOE","ACTA2","ACTG2","MYH11","RGS5")

expr.RNAscaledata.goi <- list()
colorbreaks.RNAscaledata.goi <- list()
goi.hm <- list()
for (g in names(genesofinterest)) {
  expr.RNAscaledata.goi[[g]] <- list()
  colorbreaks.RNAscaledata.goi[[g]] <- list()
  goi.hm[[g]] <- list()
  
  #Heatmaps
  expr.RNAscaledata.goi[[g]] <- expr.RNAscaledata[genesofinterest[[g]],]
  #set colorbreaks
  colorbreaks.RNAscaledata.goi[[g]] <- c(-max(abs(expr.RNAscaledata.goi[[g]])),
                                         -(mean(unlist(abs(expr.RNAscaledata.goi[[g]]))[unlist(abs(expr.RNAscaledata.goi[[g]]))!=0]) + 2*sd(unlist(abs(expr.RNAscaledata.goi[[g]]))[unlist(abs(expr.RNAscaledata.goi[[g]]))!=0])),
                                         0,
                                         mean(unlist(abs(expr.RNAscaledata.goi[[g]]))[unlist(abs(expr.RNAscaledata.goi[[g]]))!=0]) + 2*sd(unlist(abs(expr.RNAscaledata.goi[[g]]))[unlist(abs(expr.RNAscaledata.goi[[g]]))!=0]),
                                         max(abs(expr.RNAscaledata.goi[[g]])))
  
  if(g=="collagens") {rownames(expr.RNAscaledata.goi[[g]]) <- sub("COL","",rownames(expr.RNAscaledata.goi[[g]]))}
  goi.hm[[g]] <- Heatmap(expr.RNAscaledata.goi[[g]],
                         name="scale.data",
                         col=circlize::colorRamp2(breaks=colorbreaks.RNAscaledata.goi[[g]], colors = c("red","purple", "black", "yellow","white")),
                         show_column_names = F,
                         show_row_names = T,
                         cluster_columns = T,
                         cluster_column_slices = F,
                         clustering_method_columns = "ward.D2",
                         clustering_distance_columns = "euclidean",
                         column_split = HNSCC.f$fibrotype,
                         cluster_rows = T,
                         clustering_method_rows = "ward.D2",
                         clustering_distance_rows = "euclidean",
                         row_title_rot = 0,
                         column_title_rot = 90,
                         #graphic options
                         row_names_gp = gpar(fontsize=8),
                         column_names_gp = gpar(fontsize=11),
                         row_title_gp = gpar(fontsize=11),
                         column_title_gp = gpar(fontsize=11),
                         heatmap_legend_param = list(title_gp = gpar(fontsize=11), labels_gp = gpar(fontsize=11)),
                         border = T,
                         use_raster = T,
                         raster_device = "CairoPNG",
                         raster_quality = 4,
                         heatmap_height = unit(5,"in"),
                         heatmap_width = unit(5,"in"))
  
  pdf(paste0(OUTPUT,"figs/HNSCC-fibrofilt-SCTccmito-fibrotype-HM-RNAscaledata-",g,".pdf"), width=20, height=20)
  print(goi.hm[[g]])
  dev.off()
}

genesofinterest[["markers"]] <- list(
  ECM=c("MMP11","MMP1"),
  Immune=c(paste0("CXCL",c(1,2,3,5,6,8,9,10,11,12,13,14)),paste0("CCL",c(2,3,5,8,19,21)),"C3","C7","CFD","IL6","IL11","IL24","PLA2G2A","APOD","APOE"),
  Myofibroblasts=c("ACTA2","ACTG2","MYH11"),
  Pericytes=c("RGS5"))
#DotPlot
d1 <- DotPlot(HNSCC.f,
              features = genesofinterest[["markers"]],
              group.by = "fibrotype",
              col.min = NULL,
              col.max = NULL,
              assay = "RNA") +
  scale_y_discrete(position = "right") +
  labs(x="",y="") + 
  theme_jb() +
  theme(strip.text.x = element_text(size=11, angle=90, hjust=0,vjust=.5),
        axis.text.y = element_text(angle=180))

#code for changing colors of facets from https://github.com/tidyverse/ggplot2/issues/2096 
colors <- scales::hue_pal()(6)[-3]
names(colors) <- names(genesofinterest[["markers"]])

d1g <- ggplot_gtable(ggplot_build(d1))
strip_both <- which(grepl('strip-', d1g$layout$name))
fills <- c(colors)
k <- 1
for (i in strip_both) {
  j <- which(grepl('rect', d1g$grobs[[i]]$grobs[[1]]$childrenOrder))
  d1g$grobs[[i]]$grobs[[1]]$children[[j]]$gp$fill <- fills[k]
  k <- k+1
}

ggsave(filename = paste0(OUTPUT,"figs/HNSCC-fibrofilt-SCTccmito-fibrotype-DotPlot-marker.svg"),grid.draw(d1g),
       width = 7,
       height = 5)
```

## Differential expression

```{r}
HNSCC.f.fibrotype <- calculate_foldchanges(HNSCC.f,HNSCC.f$fibrotype)
#filter for genes with low foldchanges and pct value. This improves GSEA analysis because genes suffering from high dropout (i.e., lowly expressed and low signal) are not considered for ranking, while most up/downregulated genes are still preserved. These are also default values for "FindAllMarkers" function
HNSCC.f.fibrotype <- HNSCC.f.fibrotype[(HNSCC.f.fibrotype$pct.1 > 0.1 | HNSCC.f.fibrotype$pct.2 > 0.1) & abs(HNSCC.f.fibrotype$avg_log2FC)>0.25,]
```

# Volcano Plots 

```{r}
#set thres function for selecting genes to mark in volcano plot
logFCcutoff_fibrotype = function(x) {
  c(sort(HNSCC.f.fibrotype[HNSCC.f.fibrotype$cluster==x,]$avg_log2FC, decreasing = T)[11])
}
pctdiffcutoff_fibrotype = function(x) {
  c(sort(HNSCC.f.fibrotype[HNSCC.f.fibrotype$cluster==x,]$pct.1 - HNSCC.f.fibrotype[HNSCC.f.fibrotype$cluster==x,]$pct.2, decreasing = T)[21])
}

#create volcano plots with pct difference on y-axis
HNSCC.f.fibrotype.volpct <- lapply(levels(HNSCC.f.fibrotype$cluster), function(x) ggvolcano(HNSCC.f.fibrotype[HNSCC.f.fibrotype$cluster==x,],logFCcutoff_fibrotype(x),onlypos = T,pctdiff = F) + ggtitle(x))
names(HNSCC.f.fibrotype.volpct) <- levels(HNSCC.f.fibrotype$cluster)

HNSCC.f.fibrotype.volpctdiff <- lapply(levels(HNSCC.f.fibrotype$cluster), function(x) ggvolcano(HNSCC.f.fibrotype[HNSCC.f.fibrotype$cluster==x,],pctdiffcutoff_fibrotype(x),onlypos = T,pctdiff = T) + ggtitle(x))
names(HNSCC.f.fibrotype.volpctdiff) <- levels(HNSCC.f.fibrotype$cluster)

#save volcano plots
for (i in names(HNSCC.f.fibrotype.volpct)) {
  ggsave(filename = paste0(OUTPUT,"figs/HNSCC-fibrofilt-diffexpr-SCTccmito-fibrotype-volcanopct-",i,".svg"),HNSCC.f.fibrotype.volpct[[i]])
}
for (i in names(HNSCC.f.fibrotype.volpctdiff)) {
  ggsave(filename = paste0(OUTPUT,"figs/HNSCC-fibrofilt-diffexpr-SCTccmito-fibrotype-volcanopctdiff-",i,".svg"),HNSCC.f.fibrotype.volpctdiff[[i]])
}

HNSCC.f.fibrotype.volpct
```

## Gene Set Enrichment Analysis (GSEA)

```{r}
library(fgsea)

FCranks.fibrotype <- list()
for (cl in unique(HNSCC.f.fibrotype$cluster)) {
  #rank DGE results by foldchange
  FCranks.fibrotype[[cl]] <- HNSCC.f.fibrotype[HNSCC.f.fibrotype$cluster==cl,]$avg_log2FC
  names(FCranks.fibrotype[[cl]]) <- HNSCC.f.fibrotype[HNSCC.f.fibrotype$cluster==cl,]$gene
  
  #convert -Inf to -1000
  FCranks.fibrotype[[cl]][is.infinite(FCranks.fibrotype[[cl]])] <- -1000
}

#read in MsigDB pathway from downloads, in this case GO: BP
GOBP <- gmtPathways("~/tscr/kai/db/msigdb/c5.bp.v7.1.symbols.gmt")
HM <- gmtPathways("~/tscr/kai/db/msigdb/h.all.v7.1.symbols.gmt")
GS <- c(GOBP,HM)

#run fgsea
GS.gsea.fibrotype <- list()
for (cl in levels(HNSCC.f.fibrotype$cluster)) {
  GS.gsea.fibrotype[[cl]] <- fgsea(pathways=GS,
                                   stats=FCranks.fibrotype[[cl]],
                                   minSize=15,
                                   maxSize=500,
                                   nperm=10000)
}

#Plotting
#remove GO in name and put to lower cases
GS.gsea.fibrotype.plot <- lapply(GS.gsea.fibrotype,function(x) {x$pathway <- gsub("_"," ",tolower(sub("GO_","",x$pathway))); x})
#abbreviate some GO terms
GS.gsea.fibrotype.plot <- lapply(GS.gsea.fibrotype.plot,function(x) {x$pathway <- gsub("negative regulation of nucleobase containing compound metabolic process","neg. reg. of nucleobase containing compound met. process",x$pathway); x})
#Plotting
GS.gsea.fibrotypevis <- lapply(names(GS.gsea.fibrotype.plot), function(x) try(GSEAvis(GSEAdf = GS.gsea.fibrotype.plot[[x]],
                                                                                      pvalthres = NULL,
                                                                                      NESthres = NULL,
                                                                                      npathways = 5,
                                                                                      sort = "NES",
                                                                                      positive = T) +
                                                                                labs(x=x,y="") +
                                                                                scale_fill_gradientn(limits = c(0,-log10(min(unlist(lapply(GS.gsea.fibrotype.plot, function(x) {y <- x[x$ES>0,]; y[order(y$ES,decreasing = T),]$padj[1:5]}))))),colours = c("white","blue")) +
                                                                                coord_flip(ylim = c(0,max(unlist(lapply(GS.gsea.fibrotype.plot,function(x) {y <- x[x$ES>0,]; y[order(y$ES,decreasing = T),]$NES[1:5]}))))) +
                                                                                scale_y_continuous(breaks = seq(0,10,0.5))
)) 
names(GS.gsea.fibrotypevis) <- names(GS.gsea.fibrotype.plot)
lapply(names(GS.gsea.fibrotype.plot), function(x) try(ggsave(filename = paste0(OUTPUT,"figs/HNSCC-fibrofilt-diffexpr-SCTccmito-fibrotype-GS-top5byES-",x,".svg"),GS.gsea.fibrotypevis[[x]],width=10, height=5)))

#All GSEA Plots in one file
library(cowplot)
GS.gsea.fibrotypevis.comb <- lapply(1:(length(GS.gsea.fibrotypevis)-1), function(x) {
  GS.gsea.fibrotypevis[[x]] + 
    theme(axis.text.x = element_blank(), axis.ticks.x = element_blank(), axis.title.x = element_blank())
})
GS.gsea.fibrotypevis.comb[[length(GS.gsea.fibrotypevis.comb)+1]] <- GS.gsea.fibrotypevis[[length(GS.gsea.fibrotypevis)]]
try(ggsave(filename = paste0(OUTPUT,"figs/HNSCC-fibrofilt-diffexpr-SCTccmito-fibrotype-GS-top5byES-all.svg"),
           plot_grid(plotlist = GS.gsea.fibrotypevis.comb,ncol=1,align = "v",labels=NULL),
           width=5, 
           height=6))

try(ggsave(filename = paste0(OUTPUT,"figs/HNSCC-fibrofilt-diffexpr-SCTccmito-fibrotype-GS-top5byES-all-noleg.svg"),
           plot_grid(plotlist = lapply(GS.gsea.fibrotypevis.comb,function(x) x + theme(legend.position = "none")),ncol=1,align = "v",labels=NULL),
           width=5, 
           height=6))

GS.gsea.fibrotypevis.comb <- lapply(1:(length(GS.gsea.fibrotypevis)), function(x) {
  GS.gsea.fibrotypevis[[x]] + 
    theme(axis.text.x = element_blank(), axis.ticks.x = element_blank(), axis.title.x = element_blank())
})
try(ggsave(filename = paste0(OUTPUT,"figs/HNSCC-fibrofilt-diffexpr-SCTccmito-fibrotype-GS-top5byES-all-nolegaxis.svg"),
           plot_grid(plotlist = lapply(GS.gsea.fibrotypevis.comb,function(x) x + theme(legend.position = "none")),ncol=1,align = "v",labels=NULL),
           width=5, 
           height=6))
```

# Top genes

```{r}
topgenes = 5

#choose those top genes
HNSCC.f.fibrotype.percluster <- lapply(unique(HNSCC.f.fibrotype$cluster), function(x) HNSCC.f.fibrotype[HNSCC.f.fibrotype$cluster==x,])
names(HNSCC.f.fibrotype.percluster) <- unique(HNSCC.f.fibrotype$cluster)

top.logFC.fibrotype <- list()
highlightgenes.fibrotype <- list()
for (cl in names(HNSCC.f.fibrotype.percluster)) {
  #top avg FC
  top.logFC.fibrotype[[cl]] <- head(HNSCC.f.fibrotype.percluster[[cl]][order(HNSCC.f.fibrotype.percluster[[cl]]$avg_log2FC,decreasing = T),]$gene, n=topgenes)
  #create dataframe
  highlightgenes.fibrotype[[cl]] <- data.frame(genes=top.logFC.fibrotype[[cl]], state=cl)
}

# summarize in one dataframe
highlightgenes.fibrotype <- as.data.frame(data.table::rbindlist(highlightgenes.fibrotype))

expr.RNAscaledata <- as.data.frame(GetAssayData(HNSCC.f, assay = "RNA", slot = "scale.data"))
#subset expression matrix by highlight genes
expr.RNAscaledata.hl.fibrotype <- expr.RNAscaledata[as.character(highlightgenes.fibrotype$genes),]
#set colorbreaks as above
colorbreaks.RNAscaledata.hl.fibrotype <- c(-max(abs(expr.RNAscaledata.hl.fibrotype)),
                                           -(mean(unlist(abs(expr.RNAscaledata.hl.fibrotype))[unlist(abs(expr.RNAscaledata.hl.fibrotype))!=0]) + 2*sd(unlist(abs(expr.RNAscaledata.hl.fibrotype))[unlist(abs(expr.RNAscaledata.hl.fibrotype))!=0])),
                                           0,
                                           mean(unlist(abs(expr.RNAscaledata.hl.fibrotype))[unlist(abs(expr.RNAscaledata.hl.fibrotype))!=0]) + 2*sd(unlist(abs(expr.RNAscaledata.hl.fibrotype))[unlist(abs(expr.RNAscaledata.hl.fibrotype))!=0]),
                                           max(abs(expr.RNAscaledata.hl.fibrotype)))

#Heatmap clustered by columns and rows, rows split by differential expression of certain cluster
diffexprhm.hl.clustered.fibrotype <- Heatmap(expr.RNAscaledata.hl.fibrotype,
                                             name="scale.data",
                                             col=circlize::colorRamp2(breaks=colorbreaks.RNAscaledata.hl.fibrotype, colors = c("red","purple", "black", "yellow","white")),
                                             show_column_names = F,
                                             show_row_names = T,
                                             cluster_columns = T,
                                             cluster_column_slices = F,
                                             clustering_method_columns = "ward.D2",
                                             clustering_distance_columns = "euclidean",
                                             column_split = HNSCC.f$fibrotype,
                                             row_split = factor(highlightgenes.fibrotype$state, levels=levels(HNSCC.f$fibrotype)),
                                             row_order = rownames(expr.RNAscaledata.hl.fibrotype),
                                             cluster_rows = F,
                                             cluster_row_slices = F,
                                             row_title_rot = 0,
                                             column_title_rot = 90,
                                             #graphic options
                                             row_names_gp = gpar(fontsize=8),
                                             column_names_gp = gpar(fontsize=11),
                                             row_title_gp = gpar(fontsize=11),
                                             column_title_gp = gpar(fontsize=11),
                                             heatmap_legend_param = list(title_gp = gpar(fontsize=11), labels_gp = gpar(fontsize=11)),
                                             border = T,
                                             use_raster = T,
                                             raster_device = "CairoPNG",
                                             raster_quality = 4,
                                             heatmap_height = unit(5,"in"),
                                             heatmap_width = unit(5,"in"))

#Save Heatmap
pdf(paste0(OUTPUT,"figs/HNSCC-fibrofilt-diffexpr-SCTccmito-fibrotype-HM-RNAscaledata-top",as.character(topgenes),".pdf"), width=20, height=20)
diffexprhm.hl.clustered.fibrotype
dev.off()
```

## Save 

```{r}
#Single Seurat object
save(file = paste0(OUTPUT,"RData/HNSCC-fibrofilt-typeanalysis.RData"),HNSCC.f)
#SessionInfo
writeLines(capture.output(sessionInfo()), paste0(OUTPUT,"RData/HNSCC-fibrofilt-typeanalysis-sessionInfo.txt"))
```
