---
title: "epithelial"
author: "Kai"
date: "2nd July 2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(Seurat)
library(ggplot2)
library(ggrepel)

source(paste0("~/tscr/kai/projects/01_SCC_scRNA/results/functions.R"))
OUTPUT = "~/tscr/kai/projects/01_SCC_scRNA/results/samples/cohort/all/rp/"
```

# Load Seurat object

```{r}
load(paste0(OUTPUT,"RData/SCCfilt-epino1.RData"))
```

# Subset cells and evaluate subsetting

```{r}
SCC.epino1.temp <- SCC.epino1
SCC.epino1 <- subset(SCC.epino1.temp,cells = names(SCC.epino1.temp$CellType_epino1_SCTccmito_harmony)[SCC.epino1.temp$CellType_epino1_SCTccmito_harmony=="epithelial" & SCC.epino1.temp$Lok!="LN"])

DefaultAssay(SCC.epino1) <- "RNA"
SCC.epino1@assays$SCT <- NULL
SCC.epino1@assays$SCTccmito <- NULL
for (x in names(SCC.epino1@reductions)) {SCC.epino1@reductions[[x]] <- NULL}
```

# Normalization

## Normalization of RNA assay

```{r SCC_normalization}
#RNA normalization without regressing, necessary for example for differential gene expression not based on SCT.
DefaultAssay(SCC.epino1) <- "RNA"
#log-normalization for slot "data"
SCC.epino1 <- NormalizeData(SCC.epino1, 
                            normalization.method = "LogNormalize", #default
                            scale.factor = 10000, #default, scale factor 10000 is recommendation from seurat tutorial
                            assay = "RNA",
                            margin = 1 # default; normalizes across features
) 

#Find Variable Features
SCC.epino1 <- FindVariableFeatures(SCC.epino1, 
                                   assay = "RNA",
                                   selection.method = "vst", #default
                                   nfeatures = 2000 #default; only 2000 , 3000 for SCT promises since to "restore" some more VariableFeatures
)

#scaling for slot "scale.data"
SCC.epino1 <- ScaleData(SCC.epino1,
                        features = VariableFeatures(SCC.epino1,assay = "RNA"),
                        do.scale = T,
                        do.center = T,
                        scale.max = 10,
                        assay = "RNA")
```

## Determine cell cycle

```{r}
SCC.epino1 <- CellCycleScoring(SCC.epino1,
                               s.features = cc.genes.updated.2019$s.genes,
                               g2m.features = cc.genes.updated.2019$g2m.genes, 
                               assay="RNA")
```

# Regression of cell cycle and mitochondrial percentage

## Normalization with SCTransform

```{r SCC.epino1_normalization}
SCC.epino1 <- SCTransform(SCC.epino1, 
                          ncells = ncol(SCC.epino1),
                          assay="RNA", #default
                          new.assay.name = "SCTccmito", #default; overwrites old SCT
                          do.correct.umi = T, #default change counts slot to corrected counts in new assay
                          variable.features.n = 3000, #default set variable features
                          vars.to.regress = c("S.Score","G2M.Score","percent.mito"), #default optional variables to regress out
                          do.scale = F, #default scale pearson residuals in scale.data slot to have unit variance
                          do.center = T, #default center pearson residuals in scale.data to have mean zero, needed for PCA
                          return.only.var.genes = T, #default scale.data.matrices output assay only contains variable genes
                          seed.use = 1448145)
```

# Dimension reduction

## PCA

```{r}
SCC.epino1 <- RunPCA(SCC.epino1, 
                     npcs = 50,  #number of PCs to use
                     assay = "SCTccmito",
                     rev.pca = F, # default, Run cell x gene matrix
                     weight.by.var = T, #default, Weight cell embedding by variance of each PC!)
                     approx = T, #if TRUE, uses irlba instead of prcomp, which is a single value decomposition to approximate PCs, saving computation time (by not calculating all PCs; important for big datasets) and being similar/same to PCs
                     features = VariableFeatures(SCC.epino1,assay = "SCTccmito"), #default
                     reduction.name = "pca_SCTccmito",
                     verbose = F)
```

```{r}
#calculate the % variance explained
PCAvar.SCTccmito <- SCC.epino1@reductions$pca_SCTccmito@stdev^2 / sum(matrixStats::rowVars(as.matrix(SCC.epino1@assays$SCTccmito@scale.data)[VariableFeatures(SCC.epino1,assay = "SCTccmito"),]))

#PCA plot
PCAplot.SCTccmito <- DimPlot(SCC.epino1, reduction = "pca_SCTccmito", dims = c(1,2), group.by = "patient") + 
  labs(x=paste0("principal component 1 (",signif(PCAvar.SCTccmito[1]*100,digits = 2),"% of variance)"),
       y=paste0("principal component 2 (",signif(PCAvar.SCTccmito[2]*100,digits = 2),"% of variance)")) +
  theme_jb_nogrid()

#elbow plot
PCAelbowplot.SCTccmito <- ggplot(data=data.frame(var=PCAvar.SCTccmito,
                                                 PC=1:length(PCAvar.SCTccmito))[1:50,]) +
  geom_point(mapping = aes(x=PC,y=var)) +
  labs(x="principal component", y="% of variance") +
  scale_x_continuous(breaks=seq(0,50,5)) +
  theme_jb()

# cumulative variance Plot
PCAsumplot.SCTccmito <- ggplot(data=data.frame(cumvar=cumsum(PCAvar.SCTccmito),PC=1:length(PCAvar.SCTccmito))[1:50,]) +
  geom_point(mapping = aes(x=PC,y=cumvar)) +
  labs(x="principal component", y="% of cumulative variance") +
  scale_x_continuous(breaks=seq(0,50,5)) +
  theme_jb()

ggsave(filename = paste0(OUTPUT,"figs/SCCfilt-epino1filt-SCTccmito-PCA.svg"),PCAplot.SCTccmito, width = 5, height = 5)
ggsave(filename = paste0(OUTPUT,"figs/SCCfilt-epino1filt-SCTccmito-PCA-noleg.svg"),PCAplot.SCTccmito + theme(legend.position = "none") + labs(title = NULL), width = 5, height = 5)
ggsave(filename = paste0(OUTPUT,"figs/SCCfilt-epino1filt-SCTccmito-PCA-elbow.svg"),PCAelbowplot.SCTccmito, width = 5, height = 5)
ggsave(filename = paste0(OUTPUT,"figs/SCCfilt-epino1filt-SCTccmito-PCA-elbow-noleg.svg"),PCAelbowplot.SCTccmito + theme(legend.position = "none") + labs(title = NULL), width = 5, height = 5)
ggsave(filename = paste0(OUTPUT,"figs/SCCfilt-epino1filt-SCTccmito-PCA-variancesum.svg"),PCAsumplot.SCTccmito, width = 5, height = 5)
ggsave(filename = paste0(OUTPUT,"figs/SCCfilt-epino1filt-SCTccmito-PCA-variancesum-noleg.svg"),PCAsumplot.SCTccmito + theme(legend.position = "none") + labs(title = NULL), width = 5, height = 5)

PCAelbowplot.SCTccmito
PCAsumplot.SCTccmito
PCAplot.SCTccmito
```

## Graph-based clustering

```{r FindClusters}
numberofPCs = 15

DefaultAssay(SCC.epino1) <- "SCTccmito"
#based on harmony
SCC.epino1 <- FindNeighbors(SCC.epino1,
                            dims = 1:numberofPCs,
                            reduction = "pca_SCTccmito",
                            assay = "SCTccmito")
SCC.epino1 <- FindClusters(SCC.epino1,
                           resolution = 2,
                           random.seed=100)

SCC.epino1$seurat_clusters_epino1_SCTccmito_PCA <- SCC.epino1$seurat_clusters
SCC.epino1$seurat_clusters <- NULL
```

## UMAP

```{r UMAP}
SCC.epino1 <- RunUMAP(SCC.epino1,
                      dims = 1:numberofPCs,
                      assay = "SCTccmito",
                      umap.method = "uwot", # Seurat default
                      graph=NULL, #default
                      reduction="pca_SCTccmito",
                      reduction.name = "umap_SCTccmito",
                      reduction.key = "umap_SCTccmito"
)
```

```{r}
UMAP.SCTccmito.clusPCA <- DimPlot(SCC.epino1, 
                                  reduction = "umap_SCTccmito", 
                                  pt.size = 1, 
                                  label = T, 
                                  group.by = "seurat_clusters_epino1_SCTccmito_PCA") + 
  labs(x="UMAP_1",y="UMAP_2") +
  theme_jb_nogrid()

UMAP.SCTccmito.celltype.ss <- DimPlot(SCC.epino1, 
                                      reduction = "umap_SCTccmito", 
                                      pt.size = 1, 
                                      label = F, 
                                      group.by = "CellType_ss") +  
  labs(x="UMAP_1",y="UMAP_2") +
  theme_jb_nogrid()

UMAP.SCTccmito.sample <- DimPlot(SCC.epino1, 
                                 reduction = "umap_SCTccmito", 
                                 pt.size = 1, 
                                 label = F, 
                                 group.by = "sample") +  
  labs(x="UMAP_1",y="UMAP_2") +
  theme_jb_nogrid()

UMAP.SCTccmito.patients <- DimPlot(SCC.epino1, 
                                   reduction = "umap_SCTccmito", 
                                   pt.size = 1, 
                                   label = F, 
                                   group.by = "patient") + 
  labs(x="UMAP_1",y="UMAP_2") +
  theme_jb_nogrid() 

UMAP.SCTccmito.hashID <- DimPlot(SCC.epino1, 
                                 reduction = "umap_SCTccmito", 
                                 pt.size = 1, 
                                 label = F, 
                                 group.by = "hash.ID") + 
  labs(x="UMAP_1",y="UMAP_2") +
  theme_jb_nogrid() 

UMAP.SCTccmito.Lok <- DimPlot(SCC.epino1, 
                              reduction = "umap_SCTccmito", 
                              pt.size = 1, 
                              label = F, 
                              group.by = "Lok") + 
  labs(x="UMAP_1",y="UMAP_2") +
  theme_jb_nogrid() 

UMAP.SCTccmito.tech <- DimPlot(SCC.epino1, 
                               reduction = "umap_SCTccmito", 
                               pt.size = 1, 
                               label = F, 
                               group.by = "technology") + 
  labs(x="UMAP_1",y="UMAP_2") +
  theme_jb_nogrid()

UMAP.SCTccmito.lib <- DimPlot(SCC.epino1, 
                              reduction = "umap_SCTccmito", 
                              pt.size = 1, 
                              label = F, 
                              group.by = "lib") + 
  labs(x="UMAP_1",y="UMAP_2") +
  theme_jb_nogrid()

UMAP.SCTccmito.Phase <- DimPlot(SCC.epino1, 
                                reduction = "umap_SCTccmito", 
                                pt.size = 1, 
                                label = F, 
                                group.by = "Phase") + 
  labs(x="UMAP_1",y="UMAP_2") +
  theme_jb_nogrid()


UMAP.SCTccmito.QC <- FeaturePlot(SCC.epino1, 
                                 features = c("nCount_RNA_log10", "nFeature_RNA_log10", "percent.mito", "n.exp.hkgenes","S.Score","G2M.Score"), 
                                 reduction = "umap_SCTccmito", 
                                 cols = c("grey95", "blue"),
                                 pt.size = 1,
                                 ncol = 2,
                                 order = T,
                                 slot = "data")

ggsave(filename = paste0(OUTPUT,"figs/SCCfilt-epino1filt-SCTccmito-UMAP-clusPCA.svg"),UMAP.SCTccmito.clusPCA,width=5,height=5)
ggsave(filename = paste0(OUTPUT,"figs/SCCfilt-epino1filt-SCTccmito-UMAP-clusPCA-noleg.svg"),UMAP.SCTccmito.clusPCA + theme(legend.position = "none"),width=5,height=5)
ggsave(filename = paste0(OUTPUT,"figs/SCCfilt-epino1filt-SCTccmito-UMAP-CellType-ss.svg"),UMAP.SCTccmito.celltype.ss,width=5,height=5)
ggsave(filename = paste0(OUTPUT,"figs/SCCfilt-epino1filt-SCTccmito-UMAP-CellType-ss-noleg.svg"),UMAP.SCTccmito.celltype.ss + theme(legend.position = "none"),width=5,height=5)
ggsave(filename = paste0(OUTPUT,"figs/SCCfilt-epino1filt-SCTccmito-UMAP-sample.svg"),UMAP.SCTccmito.sample,width=5,height=5)
ggsave(filename = paste0(OUTPUT,"figs/SCCfilt-epino1filt-SCTccmito-UMAP-sample-noleg.svg"),UMAP.SCTccmito.sample + theme(legend.position = "none"),width=5,height=5)
ggsave(filename = paste0(OUTPUT,"figs/SCCfilt-epino1filt-SCTccmito-UMAP-patients.svg"),UMAP.SCTccmito.patients,width=5,height=5)
ggsave(filename = paste0(OUTPUT,"figs/SCCfilt-epino1filt-SCTccmito-UMAP-patients-noleg.svg"),UMAP.SCTccmito.patients + theme(legend.position = "none"),width=5,height=5)
ggsave(filename = paste0(OUTPUT,"figs/SCCfilt-epino1filt-SCTccmito-UMAP-hashID.svg"),UMAP.SCTccmito.hashID,width=5,height=5)
ggsave(filename = paste0(OUTPUT,"figs/SCCfilt-epino1filt-SCTccmito-UMAP-hashID-noleg.svg"),UMAP.SCTccmito.hashID + theme(legend.position = "none"),width=5,height=5)
ggsave(filename = paste0(OUTPUT,"figs/SCCfilt-epino1filt-SCTccmito-UMAP-Lok.svg"),UMAP.SCTccmito.Lok,width=5,height=5)
ggsave(filename = paste0(OUTPUT,"figs/SCCfilt-epino1filt-SCTccmito-UMAP-Lok-noleg.svg"),UMAP.SCTccmito.Lok + theme(legend.position = "none"),width=5,height=5)
ggsave(filename = paste0(OUTPUT,"figs/SCCfilt-epino1filt-SCTccmito-UMAP-technology.svg"),UMAP.SCTccmito.tech,width=5,height=5)
ggsave(filename = paste0(OUTPUT,"figs/SCCfilt-epino1filt-SCTccmito-UMAP-technology-noleg.svg"),UMAP.SCTccmito.tech + theme(legend.position = "none"),width=5,height=5)
ggsave(filename = paste0(OUTPUT,"figs/SCCfilt-epino1filt-SCTccmito-UMAP-lib.svg"),UMAP.SCTccmito.lib,width=5,height=5)
ggsave(filename = paste0(OUTPUT,"figs/SCCfilt-epino1filt-SCTccmito-UMAP-lib-noleg.svg"),UMAP.SCTccmito.lib + theme(legend.position = "none"),width=5,height=5)
ggsave(filename = paste0(OUTPUT,"figs/SCCfilt-epino1filt-SCTccmito-UMAP-Phase.svg"),UMAP.SCTccmito.Phase,width=5,height=5)
ggsave(filename = paste0(OUTPUT,"figs/SCCfilt-epino1filt-SCTccmito-UMAP-Phase-noleg.svg"),UMAP.SCTccmito.Phase + theme(legend.position = "none"),width=5,height=5)
ggsave(filename = paste0(OUTPUT,"figs/SCCfilt-epino1filt-SCTccmito-UMAP-QC.svg"),UMAP.SCTccmito.QC, width=10, height=15)

UMAP.SCTccmito.clusPCA
UMAP.SCTccmito.celltype.ss
UMAP.SCTccmito.sample
UMAP.SCTccmito.patients
UMAP.SCTccmito.hashID
UMAP.SCTccmito.Lok
UMAP.SCTccmito.tech
UMAP.SCTccmito.lib
UMAP.SCTccmito.Phase
UMAP.SCTccmito.QC
```

# Harmony batch correction

```{r}
library(harmony)
set.seed(42)
SCC.epino1 <- RunHarmony(SCC.epino1,
                         reduction="pca_SCTccmito",
                         group.by.vars = "patient",
                         reduction.save = "harmony_SCTccmito",
                         plot_convergence = T,
                         max.iter.harmony = 30,
                         assay.use = "SCTccmito",
                         project.dim = F)
```

## Graph-based clustering

```{r FindClusters}
numberofPCs = 15

DefaultAssay(SCC.epino1) <- "SCTccmito"
#based on harmony
SCC.epino1 <- FindNeighbors(SCC.epino1,
                            dims = 1:numberofPCs,
                            reduction = "harmony_SCTccmito",
                            assay = "SCTccmito")
SCC.epino1 <- FindClusters(SCC.epino1,
                           resolution = 0.8,
                           random.seed=100)

SCC.epino1$seurat_clusters_epino1_SCTccmito_PCA_harmony <- SCC.epino1$seurat_clusters
SCC.epino1$seurat_clusters <- NULL
```

## UMAP

```{r UMAP}
SCC.epino1 <- RunUMAP(SCC.epino1,
                      dims = 1:numberofPCs,
                      assay = "SCTccmito",
                      umap.method = "uwot", # Seurat default
                      graph=NULL, #default
                      reduction="harmony_SCTccmito",
                      reduction.name = "humap_SCTccmito",
                      reduction.key = "humap_SCTccmito"
)
```

```{r}
UMAPharmony.SCTccmito.clusPCA <- DimPlot(SCC.epino1, 
                                         reduction = "humap_SCTccmito", 
                                         pt.size = 1, 
                                         label = T, 
                                         group.by = "seurat_clusters_epino1_SCTccmito_PCA_harmony") + 
  labs(x="UMAP_1",y="UMAP_2") +
  theme_jb_nogrid()

UMAPharmony.SCTccmito.celltype.ss <- DimPlot(SCC.epino1, 
                                             reduction = "humap_SCTccmito", 
                                             pt.size = 1, 
                                             label = F, 
                                             group.by = "CellType_ss") +  
  labs(x="UMAP_1",y="UMAP_2") +
  theme_jb_nogrid()

UMAPharmony.SCTccmito.sample <- DimPlot(SCC.epino1, 
                                        reduction = "humap_SCTccmito", 
                                        pt.size = 1, 
                                        label = F, 
                                        group.by = "sample") +  
  labs(x="UMAP_1",y="UMAP_2") +
  theme_jb_nogrid()

UMAPharmony.SCTccmito.patients <- DimPlot(SCC.epino1, 
                                          reduction = "humap_SCTccmito", 
                                          pt.size = 1, 
                                          label = F, 
                                          group.by = "patient") + 
  labs(x="UMAP_1",y="UMAP_2") +
  theme_jb_nogrid() 

UMAPharmony.SCTccmito.hashID <- DimPlot(SCC.epino1, 
                                        reduction = "humap_SCTccmito", 
                                        pt.size = 1, 
                                        label = F, 
                                        group.by = "hash.ID") + 
  labs(x="UMAP_1",y="UMAP_2") +
  theme_jb_nogrid() 

UMAPharmony.SCTccmito.Lok <- DimPlot(SCC.epino1, 
                                     reduction = "humap_SCTccmito", 
                                     pt.size = 1, 
                                     label = F, 
                                     group.by = "Lok") + 
  labs(x="UMAP_1",y="UMAP_2") +
  theme_jb_nogrid() 

UMAPharmony.SCTccmito.tech <- DimPlot(SCC.epino1, 
                                      reduction = "humap_SCTccmito", 
                                      pt.size = 1, 
                                      label = F, 
                                      group.by = "technology") + 
  labs(x="UMAP_1",y="UMAP_2") +
  theme_jb_nogrid()

UMAPharmony.SCTccmito.lib <- DimPlot(SCC.epino1, 
                                     reduction = "humap_SCTccmito", 
                                     pt.size = 1, 
                                     label = F, 
                                     group.by = "lib") + 
  labs(x="UMAP_1",y="UMAP_2") +
  theme_jb_nogrid()

UMAPharmony.SCTccmito.Phase <- DimPlot(SCC.epino1, 
                                       reduction = "humap_SCTccmito", 
                                       pt.size = 1, 
                                       label = F, 
                                       group.by = "Phase") + 
  labs(x="UMAP_1",y="UMAP_2") +
  theme_jb_nogrid()


UMAPharmony.SCTccmito.QC <- FeaturePlot(SCC.epino1, 
                                        features = c("nCount_RNA_log10", "nFeature_RNA_log10", "percent.mito", "n.exp.hkgenes","S.Score","G2M.Score"), 
                                        reduction = "humap_SCTccmito", 
                                        cols = c("grey95", "blue"),
                                        pt.size = 1,
                                        ncol = 2,
                                        order = T,
                                        slot = "data")

ggsave(filename = paste0(OUTPUT,"figs/SCCfilt-epino1filt-SCTccmito-UMAPharmony-clusPCA.svg"),UMAPharmony.SCTccmito.clusPCA,width=5,height=5)
ggsave(filename = paste0(OUTPUT,"figs/SCCfilt-epino1filt-SCTccmito-UMAPharmony-clusPCA-noleg.svg"),UMAPharmony.SCTccmito.clusPCA + theme(legend.position = "none"),width=5,height=5)
ggsave(filename = paste0(OUTPUT,"figs/SCCfilt-epino1filt-SCTccmito-UMAPharmony-CellType-ss.svg"),UMAPharmony.SCTccmito.celltype.ss,width=5,height=5)
ggsave(filename = paste0(OUTPUT,"figs/SCCfilt-epino1filt-SCTccmito-UMAPharmony-CellType-ss-noleg.svg"),UMAPharmony.SCTccmito.celltype.ss + theme(legend.position = "none"),width=5,height=5)
ggsave(filename = paste0(OUTPUT,"figs/SCCfilt-epino1filt-SCTccmito-UMAPharmony-sample.svg"),UMAPharmony.SCTccmito.sample,width=5,height=5)
ggsave(filename = paste0(OUTPUT,"figs/SCCfilt-epino1filt-SCTccmito-UMAPharmony-sample-noleg.svg"),UMAPharmony.SCTccmito.sample + theme(legend.position = "none"),width=5,height=5)
ggsave(filename = paste0(OUTPUT,"figs/SCCfilt-epino1filt-SCTccmito-UMAPharmony-patients.svg"),UMAPharmony.SCTccmito.patients,width=5,height=5)
ggsave(filename = paste0(OUTPUT,"figs/SCCfilt-epino1filt-SCTccmito-UMAPharmony-patients-noleg.svg"),UMAPharmony.SCTccmito.patients + theme(legend.position = "none"),width=5,height=5)
ggsave(filename = paste0(OUTPUT,"figs/SCCfilt-epino1filt-SCTccmito-UMAPharmony-hashID.svg"),UMAPharmony.SCTccmito.hashID,width=5,height=5)
ggsave(filename = paste0(OUTPUT,"figs/SCCfilt-epino1filt-SCTccmito-UMAPharmony-hashID-noleg.svg"),UMAPharmony.SCTccmito.hashID + theme(legend.position = "none"),width=5,height=5)
ggsave(filename = paste0(OUTPUT,"figs/SCCfilt-epino1filt-SCTccmito-UMAPharmony-Lok.svg"),UMAPharmony.SCTccmito.Lok,width=5,height=5)
ggsave(filename = paste0(OUTPUT,"figs/SCCfilt-epino1filt-SCTccmito-UMAPharmony-Lok-noleg.svg"),UMAPharmony.SCTccmito.Lok + theme(legend.position = "none"),width=5,height=5)
ggsave(filename = paste0(OUTPUT,"figs/SCCfilt-epino1filt-SCTccmito-UMAPharmony-technology.svg"),UMAPharmony.SCTccmito.tech,width=5,height=5)
ggsave(filename = paste0(OUTPUT,"figs/SCCfilt-epino1filt-SCTccmito-UMAPharmony-technology-noleg.svg"),UMAPharmony.SCTccmito.tech + theme(legend.position = "none"),width=5,height=5)
ggsave(filename = paste0(OUTPUT,"figs/SCCfilt-epino1filt-SCTccmito-UMAPharmony-lib.svg"),UMAPharmony.SCTccmito.lib,width=5,height=5)
ggsave(filename = paste0(OUTPUT,"figs/SCCfilt-epino1filt-SCTccmito-UMAPharmony-lib-noleg.svg"),UMAPharmony.SCTccmito.lib + theme(legend.position = "none"),width=5,height=5)
ggsave(filename = paste0(OUTPUT,"figs/SCCfilt-epino1filt-SCTccmito-UMAPharmony-Phase.svg"),UMAPharmony.SCTccmito.Phase,width=5,height=5)
ggsave(filename = paste0(OUTPUT,"figs/SCCfilt-epino1filt-SCTccmito-UMAPharmony-Phase-noleg.svg"),UMAPharmony.SCTccmito.Phase + theme(legend.position = "none"),width=5,height=5)
ggsave(filename = paste0(OUTPUT,"figs/SCCfilt-epino1filt-SCTccmito-UMAPharmony-QC.svg"),UMAPharmony.SCTccmito.QC, width=10, height=15)

UMAPharmony.SCTccmito.clusPCA
UMAPharmony.SCTccmito.celltype.ss
UMAPharmony.SCTccmito.sample
UMAPharmony.SCTccmito.patients
UMAPharmony.SCTccmito.hashID
UMAPharmony.SCTccmito.Lok
UMAPharmony.SCTccmito.tech
UMAPharmony.SCTccmito.lib
UMAPharmony.SCTccmito.Phase
UMAPharmony.SCTccmito.QC
```

#Save

```{r}
#Single Seurat object
save(file = paste0(OUTPUT,"RData/SCCfilt-epino1filt.RData"),SCC.epino1)
#SessionInfo
writeLines(capture.output(sessionInfo()), paste0(OUTPUT,"RData/SCCfilt-epino1filt-sessionInfo.txt"))
```