---
title: "Differential Expression"
author: "Kai"
date: "27th July 2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(Seurat)
library(ggplot2)
library(ggrepel)
library(ComplexHeatmap)
library(RColorBrewer)
library(cowplot)
library(fgsea)

source(paste0("~/tscr/kai/projects/01_SCC_scRNA/results/functions.R"))
OUTPUT = "~/tscr/kai/projects/01_SCC_scRNA/results/samples/cohort/patient1/"
```

# Load 

```{r}
load(paste0(OUTPUT,"RData/patient1-tumorfilt-typeanalysis.RData"))
```

## Differential expression

```{r}
patient1.tumor.tumortype_ov <- calculate_foldchanges(patient1.tumor,patient1.tumor$tumortype_ov)
#filter for genes with low foldchanges and pct value. This improves GSEA analysis because genes suffering from high dropout (i.e., lowly expressed and low signal) are not considered for ranking, while most up/downregulated genes are still preserved. These are also default values for "FindAllMarkers" function
patient1.tumor.tumortype_ov <- patient1.tumor.tumortype_ov[(patient1.tumor.tumortype_ov$pct.1 > 0.1 | patient1.tumor.tumortype_ov$pct.2 > 0.1) & abs(patient1.tumor.tumortype_ov$avg_log2FC)>0.25,]
```

## Volcano Plots 

```{r}
#set thres function for selecting genes to mark in volcano plot
logFCcutoff_tumortype_ov = function(x) {
  c(sort(patient1.tumor.tumortype_ov[patient1.tumor.tumortype_ov$cluster==x,]$avg_log2FC, decreasing = T)[11])
}
pctdiffcutoff_tumortype_ov = function(x) {
  c(sort(patient1.tumor.tumortype_ov[patient1.tumor.tumortype_ov$cluster==x,]$pct.1 - patient1.tumor.tumortype_ov[patient1.tumor.tumortype_ov$cluster==x,]$pct.2, decreasing = T)[21])
}

#create volcano plots with pct difference on y-axis
patient1.tumor.tumortype_ov.volpct <- lapply(levels(patient1.tumor.tumortype_ov$cluster), function(x) ggvolcano(patient1.tumor.tumortype_ov[patient1.tumor.tumortype_ov$cluster==x,],logFCcutoff_tumortype_ov(x),onlypos = T,pctdiff = F) + ggtitle(x))
names(patient1.tumor.tumortype_ov.volpct) <- levels(patient1.tumor.tumortype_ov$cluster)

patient1.tumor.tumortype_ov.volpctdiff <- lapply(levels(patient1.tumor.tumortype_ov$cluster), function(x) ggvolcano(patient1.tumor.tumortype_ov[patient1.tumor.tumortype_ov$cluster==x,],pctdiffcutoff_tumortype_ov(x),onlypos = T,pctdiff = T) + ggtitle(x))
names(patient1.tumor.tumortype_ov.volpctdiff) <- levels(patient1.tumor.tumortype_ov$cluster)

#save volcano plots
for (i in names(patient1.tumor.tumortype_ov.volpct)) {
  ggsave(filename = paste0(OUTPUT,"figs/patient1-tumorfilt-diffexpr-SCTccmito-tumortype_ov-volcanopct-",gsub("[/]","",sub(" ","",sub("[)]","",sub("[(]","",i)))),".svg"),patient1.tumor.tumortype_ov.volpct[[i]])
}
for (i in names(patient1.tumor.tumortype_ov.volpctdiff)) {
  ggsave(filename = paste0(OUTPUT,"figs/patient1-tumorfilt-diffexpr-SCTccmito-tumortype_ov-volcanopctdiff-",gsub("[/]","",sub(" ","",sub("[)]","",sub("[(]","",i)))),".svg"),patient1.tumor.tumortype_ov.volpctdiff[[i]])
}

patient1.tumor.tumortype_ov.volpct
```

## Gene Set Enrichment Analysis (GSEA)

```{r}
FCranks.tumortype_ov <- list()
for (cl in unique(patient1.tumor.tumortype_ov$cluster)) {
  #rank DGE results by foldchange
  FCranks.tumortype_ov[[cl]] <- patient1.tumor.tumortype_ov[patient1.tumor.tumortype_ov$cluster==cl,]$avg_log2FC
  names(FCranks.tumortype_ov[[cl]]) <- patient1.tumor.tumortype_ov[patient1.tumor.tumortype_ov$cluster==cl,]$gene
  
  #convert -Inf to -1000
  FCranks.tumortype_ov[[cl]][is.infinite(FCranks.tumortype_ov[[cl]])] <- -1000
}

#read in MsigDB pathway from downloads, in this case GO: BP
GOBP <- gmtPathways("~/tscr/kai/db/msigdb/c5.bp.v7.1.symbols.gmt")
HM <- gmtPathways("~/tscr/kai/db/msigdb/h.all.v7.1.symbols.gmt")

GS <- c(GOBP,HM)

#run fgsea
GS.gsea.tumortype_ov <- list()
for (cl in levels(patient1.tumor.tumortype_ov$cluster)) {
  GS.gsea.tumortype_ov[[cl]] <- fgsea(pathways=GS,
                                      stats=FCranks.tumortype_ov[[cl]],
                                      minSize=15,
                                      maxSize=500,
                                      nperm=10000)
}

#remove GO in name and put to lower cases
GS.gsea.tumortype_ov.plot <- lapply(GS.gsea.tumortype_ov,function(x) {x$pathway <- gsub("_"," ",tolower(sub("GO_","",x$pathway))); x})
#abbreviate some GO terms
GS.gsea.tumortype_ov.plot <- lapply(GS.gsea.tumortype_ov.plot,function(x) {x$pathway <- gsub("endoplasmic reticulum","ER",
                                                                                             gsub("nonsense mediated decay","NMD",x$pathway)); x})
#Plotting
numberofGS = 5

GS.gseavis.tumortype_ov <- lapply(names(GS.gsea.tumortype_ov.plot), function(x) {
  try(GSEAvis(GSEAdf = GS.gsea.tumortype_ov.plot[[x]],
              pvalthres = NULL,
              NESthres = NULL,
              npathways = numberofGS,
              sort = "NES",
              positive = T) +
        labs(x=x,y="") +
        scale_fill_gradientn(limits = c(0,-log10(min(unlist(lapply(GS.gsea.tumortype_ov.plot,function(x) {y <- x[x$NES>0,]; y[order(y$NES,decreasing = T),]$padj[1:numberofGS]}))))),
                             colours = c("white","blue")) +
        coord_flip(ylim = c(0,max(unlist(lapply(GS.gsea.tumortype_ov.plot,function(x) {y <- x[x$NES>0,]; y[order(y$NES,decreasing = T),]$NES[1:numberofGS]}))))) +
        scale_y_continuous(breaks = seq(0,20,0.5))
  )}) 
names(GS.gseavis.tumortype_ov) <- names(GS.gsea.tumortype_ov.plot)
lapply(names(GS.gsea.tumortype_ov.plot), function(x) try(ggsave(filename = paste0(OUTPUT,"figs/patient1-tumorfilt-diffexpr-SCTccmito-tumortype_ov-GS-top",numberofGS,"byNES-",gsub("[/]","",sub(" ","",sub("[)]","",sub("[(]","",x)))),".svg"),GS.gseavis.tumortype_ov[[x]],width=10, height=5)))

#All GSEA Plots in one file
library(cowplot)
GS.gseavis.tumortype_ov.comb <- lapply(1:(length(GS.gseavis.tumortype_ov)-1), function(x) {
  GS.gseavis.tumortype_ov[[x]] + 
    theme(axis.text.x = element_blank(), axis.ticks.x = element_blank(), axis.title.x = element_blank())
})
GS.gseavis.tumortype_ov.comb[[length(GS.gseavis.tumortype_ov.comb)+1]] <- GS.gseavis.tumortype_ov[[length(GS.gseavis.tumortype_ov)]]
try(ggsave(filename = paste0(OUTPUT,"figs/patient1-tumorfilt-diffexpr-SCTccmito-tumortype_ov-GS-top",numberofGS,"byNES-all.svg"),
           plot_grid(plotlist = GS.gseavis.tumortype_ov.comb,ncol=1,align = "v",labels=NULL),
           width=5, 
           height=7))

try(ggsave(filename = paste0(OUTPUT,"figs/patient1-tumorfilt-diffexpr-SCTccmito-tumortype_ov-GS-top",numberofGS,"byNES-all-noleg.svg"),
           plot_grid(plotlist = lapply(GS.gseavis.tumortype_ov.comb,function(x) x + theme(legend.position = "none")),ncol=1,align = "v",labels=NULL),
           width=5, 
           height=7))

GS.gseavis.tumortype_ov.comb <- lapply(1:(length(GS.gseavis.tumortype_ov)), function(x) {
  GS.gseavis.tumortype_ov[[x]] + 
    theme(axis.text.x = element_blank(), axis.ticks.x = element_blank(), axis.title.x = element_blank())
})
try(ggsave(filename = paste0(OUTPUT,"figs/patient1-tumorfilt-diffexpr-SCTccmito-tumortype_ov-GS-top",numberofGS,"byNES-all-nolegaxis.svg"),
           plot_grid(plotlist = lapply(GS.gseavis.tumortype_ov.comb,function(x) x + theme(legend.position = "none")),ncol=1,align = "v",labels=NULL),
           width=5, 
           height=7))
```


# GSEA plots 

```{r}
#Enrichment plots for publication (based on GSEA results inclusion)
names(FCranks.tumortype_ov)[which(names(FCranks.tumortype_ov)=="Immune (CXCL1/2/3/8)")] <- "Immune"

#EMT
HMEMT.plot <- lapply(FCranks.tumortype_ov, function(x) plotEnrichment(GS$HALLMARK_EPITHELIAL_MESENCHYMAL_TRANSITION ,x))
names(HMEMT.plot) <- names(FCranks.tumortype_ov)

for (x in names(HMEMT.plot)) {
  ggsave(filename = paste0(OUTPUT,"figs/patient1-tumorfilt-diffexpr-GSEAenrich-hallmarkEMT-",x,".svg"),HMEMT.plot[[x]],width=5,height=5)
}
```

## Heatmap of top differentially expressed genes

```{r}
topgenes = 10

#choose those top genes
patient1.tumor.tumortype_ov.percluster <- lapply(unique(patient1.tumor.tumortype_ov$cluster), function(x) patient1.tumor.tumortype_ov[patient1.tumor.tumortype_ov$cluster==x,])
names(patient1.tumor.tumortype_ov.percluster) <- unique(patient1.tumor.tumortype_ov$cluster)

top.logFC.tumortype_ov <- list()
highlightgenes.tumortype_ov <- list()
for (cl in names(patient1.tumor.tumortype_ov.percluster)) {
  #top avg FC
  top.logFC.tumortype_ov[[cl]] <- head(patient1.tumor.tumortype_ov.percluster[[cl]][order(patient1.tumor.tumortype_ov.percluster[[cl]]$avg_log2FC,decreasing = T),]$gene, n=topgenes)
  #create dataframe
  highlightgenes.tumortype_ov[[cl]] <- data.frame(genes=top.logFC.tumortype_ov[[cl]], state=cl)
}

# summarize in one dataframe
highlightgenes.tumortype_ov <- as.data.frame(data.table::rbindlist(highlightgenes.tumortype_ov))

patient1.tumor <- ScaleData(patient1.tumor,
                            features = as.character(highlightgenes.tumortype_ov$genes),
                            do.scale = T,
                            do.center = T,
                            scale.max = 10,
                            assay = "RNA")
expr.RNAscaledata <- as.data.frame(GetAssayData(patient1.tumor, assay = "RNA", slot = "scale.data"))
#subset expression matrix by highlight genes
expr.RNAscaledata.hl.tumortype_ov <- expr.RNAscaledata[as.character(highlightgenes.tumortype_ov$genes),]
#set colorbreaks as above
colorbreaks.RNAscaledata.hl.tumortype_ov <- c(-max(abs(expr.RNAscaledata.hl.tumortype_ov)),
                                              -(mean(unlist(abs(expr.RNAscaledata.hl.tumortype_ov))[unlist(abs(expr.RNAscaledata.hl.tumortype_ov))!=0]) + 2*sd(unlist(abs(expr.RNAscaledata.hl.tumortype_ov))[unlist(abs(expr.RNAscaledata.hl.tumortype_ov))!=0])),
                                              0,
                                              mean(unlist(abs(expr.RNAscaledata.hl.tumortype_ov))[unlist(abs(expr.RNAscaledata.hl.tumortype_ov))!=0]) + 2*sd(unlist(abs(expr.RNAscaledata.hl.tumortype_ov))[unlist(abs(expr.RNAscaledata.hl.tumortype_ov))!=0]),
                                              max(abs(expr.RNAscaledata.hl.tumortype_ov)))

#Heatmap clustered by columns and rows, rows split by differential expression of certain cluster
expr.RNAscaledata.hl.tumortype_ov.hm <- Heatmap(expr.RNAscaledata.hl.tumortype_ov,
                                                name="scale.data",
                                                col=circlize::colorRamp2(breaks=colorbreaks.RNAscaledata.hl.tumortype_ov, colors = c("red","purple", "black", "yellow","white")),
                                                show_column_names = F,
                                                show_row_names = T,
                                                cluster_columns = T,
                                                cluster_column_slices = F,
                                                clustering_method_columns = "ward.D2",
                                                clustering_distance_columns = "euclidean",
                                                column_split = patient1.tumor$tumortype_ov,
                                                row_split = factor(highlightgenes.tumortype_ov$state, levels = levels(patient1.tumor$tumortype_ov)),
                                                cluster_rows = F, row_order = highlightgenes.tumortype_ov$genes,
                                                row_title_rot = 0,
                                                column_title_rot = 90,
                                                #graphic options
                                                column_dend_height = unit(0.1,"in"),
                                                row_names_gp = gpar(fontsize=7),
                                                column_names_gp = gpar(fontsize=11),
                                                row_title_gp = gpar(fontsize=11),
                                                column_title_gp = gpar(fontsize=11),
                                                heatmap_legend_param = list(title_gp = gpar(fontsize=11), labels_gp = gpar(fontsize=11)),
                                                border = T,
                                                use_raster = T,
                                                raster_device = "CairoPNG",
                                                raster_quality = 4,
                                                height = unit(6,"in"),
                                                width = unit(5,"in"))
#Save Heatmap
pdf(paste0(OUTPUT,"figs/patient1-tumorfilt-diffexpr-SCTccmito-tumortype_ov-HM-RNAscaledata-top",as.character(topgenes),".pdf"), width=20, height=20)
expr.RNAscaledata.hl.tumortype_ov.hm
dev.off()
```

```{r}
#SessionInfo
writeLines(capture.output(sessionInfo()), paste0(OUTPUT,"RData/patient1-tumorfilt-diffexpr-tumortype_ov-sessionInfo.txt"))
```
